# Prerequisites

In [1]:
%cd /dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5/
#import sys
#print(sys.version)
#!python3 --version

/dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5

/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [3]:
!pip uninstall transformers -y
!pip install transformers==4.36.2  datasets==4.3.0 accelerate==0.27.2
!pip install torch==2.9.1
!pip install ipywidgets==8.1.7
!pip install python-dotenv==1.2.1 pickleshare==0.7.5

WARNING: Skipping transformers as it is not installed.
Collecting transformers==4.36.2
  Using cached transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
Collecting datasets==4.3.0
  Using cached datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Collecting accelerate==0.27.2
  Using cached accelerate-0.27.2-py3-none-any.whl.metadata (18 kB)
Collecting filelock (from transformers==4.36.2)
  Using cached filelock-3.20.3-py3-none-any.whl.metadata (2.1 kB)
Collecting huggingface-hub<1.0,>=0.19.3 (from transformers==4.36.2)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (6.0.1)
Collecting regex!=2019.12.17 (from transformers==4.36.2)
  Using cached regex-2026.1.15-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (2.32.3)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.36.2)
  Using cached tokenizers-0.15.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting safetensors>=0.3.1 (from transformers==4.36.2)
  Using cached safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting tqdm>=4.27 (from transformers==4.36.2)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.7/57.7 kB 984.7 kB/s eta 0:00:00 0:00:01
Collecting pyarrow>=21.0.0 (from datasets==4.3.0)
  Using cached pyarrow-23.0.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting dill<0.4.1,>=0.3.0 (from datasets==4.3.0)
  Using cached dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets==4.3.0) (2.2.1)
Collecting httpx<1.0.0 (from datasets==4.3.0)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting xxhash (from datasets==4.3.0)
  Using cached xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting multiprocess<0.70.17 (from datasets==4.3.0)
  Using cached multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (2024.5.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate==0.27.2) (5.9.8)
Collecting torch>=1.10.0 (from accelerate==0.27.2)
  Using cached torch-2.10.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (31 kB)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (3.9.5)
Collecting anyio (from httpx<1.0.0->datasets==4.3.0)
  Using cached anyio-4.12.1-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets==4.3.0) (2024.6.2)
Collecting httpcore==1.* (from httpx<1.0.0->datasets==4.3.0)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets==4.3.0) (3.7)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets==4.3.0)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2)
  Using cached hf_xet-1.2.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2) (4.12.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (2.0.7)
Collecting sympy>=1.13.3 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.1.4)
Collecting cuda-bindings==12.9.4 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached cuda_bindings-12.9.4-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cudnn-cu12==9.10.2.21 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparselt-cu12==0.7.1 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl.metadata (7.0 kB)
Collecting nvidia-nccl-cu12==2.27.5 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.0 kB)
Collecting nvidia-nvshmem-cu12==3.4.5 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.6.0 (from torch>=1.10.0->accelerate==0.27.2)
  Using cached triton-3.6.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Collecting cuda-pathfinder~=1.1 (from cuda-bindings==12.9.4->torch>=1.10.0->accelerate==0.27.2)
  Using cached cuda_pathfinder-1.3.3-py3-none-any.whl.metadata (1.9 kB)

Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets==4.3.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets==4.3.0) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets==4.3.0) (2024.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==4.3.0) (1.16.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.27.2)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx<1.0.0->datasets==4.3.0) (1.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate==0.27.2) (2.1.5)
Using cached transformers-4.36.2-py3-none-any.whl (8.2 MB)
Using cached datasets-4.3.0-py3-none-any.whl (506 kB)
Using cached accelerate-0.27.2-py3-none-any.whl (279 kB)
Using cached dill-0.4.0-py3-none-any.whl (119 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 3.9 MB/s eta 0:00:0000:0100:01
Using cached multiprocess-0.70.16-py310-none-any.whl (134 kB)
Using cached pyarrow-23.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (47.5 MB)
Using cached regex-2026.1.15-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (791 kB)
Using cached safetensors-0.7.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (507 kB)
Using cached tokenizers-0.15.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
Using cached torch-2.10.0-cp310-cp310-manylinux_2_28_x86_64.whl (915.6 MB)
Using cached cuda_bindings-12.9.4-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.1 MB)
Using cached nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl (594.3 MB)
Using cached nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.2 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (88.0 MB)
Using cached nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (954 kB)
Using cached nvidia_cudnn_cu12-9.10.2.21-py3-none-manylinux_2_27_x86_64.whl (706.8 MB)
Using cached nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (193.1 MB)
Using cached nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.2 MB)
Using cached nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl (63.6 MB)
Using cached nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl (267.5 MB)
Using cached nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (288.2 MB)
Using cached nvidia_cusparselt_cu12-0.7.1-py3-none-manylinux2014_x86_64.whl (287.2 MB)
Using cached nvidia_nccl_cu12-2.27.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (322.3 MB)
Using cached nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl (39.3 MB)
Using cached nvidia_nvshmem_cu12-3.4.5-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (139.1 MB)
Using cached nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (89 kB)
Using cached triton-3.6.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (188.1 MB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 1.8 MB/s eta 0:00:00ta 0:00:01
Using cached filelock-3.20.3-py3-none-any.whl (16 kB)
Using cached xxhash-3.6.0-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (193 kB)
Using cached hf_xet-1.2.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached anyio-4.12.1-py3-none-any.whl (113 kB)
Using cached cuda_pathfinder-1.3.3-py3-none-any.whl (27 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: nvidia-cusparselt-cu12, mpmath, xxhash, triton, tqdm, sympy, safetensors, regex, pyarrow, nvidia-nvtx-cu12, nvidia-nvshmem-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufile-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, hf-xet, h11, filelock, dill, cuda-pathfinder, anyio, nvidia-cusparse-cu12, nvidia-cufft-cu12, nvidia-cudnn-cu12, multiprocess, huggingface-hub, httpcore, cuda-bindings, tokenizers, nvidia-cusolver-cu12, httpx, transformers, torch, datasets, accelerate
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf 24.4.0 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 23.0.0 which is incompatible.
Successfully installed accelerate-0.27.2 anyio-4.12.1 cuda-bindings-12.9.4 cuda-pathfinder-1.3.3 datasets-4.3.0 dill-0.4.0 filelock-3.20.3 h11-0.16.0 hf-xet-1.2.0 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-0.36.2 mpmath-1.3.0 multiprocess-0.70.16 nvidia-cublas-cu12-12.8.4.1 nvidia-cuda-cupti-cu12-12.8.90 nvidia-cuda-nvrtc-cu12-12.8.93 nvidia-cuda-runtime-cu12-12.8.90 nvidia-cudnn-cu12-9.10.2.21 nvidia-cufft-cu12-11.3.3.83 nvidia-cufile-cu12-1.13.1.3 nvidia-curand-cu12-10.3.9.90 nvidia-cusolver-cu12-11.7.3.90 nvidia-cusparse-cu12-12.5.8.93 nvidia-cusparselt-cu12-0.7.1 nvidia-nccl-cu12-2.27.5 nvidia-nvjitlink-cu12-12.8.93 nvidia-nvshmem-cu12-3.4.5 nvidia-nvtx-cu12-12.8.90 pyarrow-23.0.0 regex-2026.1.15 safetensors-0.7.0 sympy-1.14.0 tokenizers-0.15.2 torch-2.10.0 tqdm-4.67.3 transformers-4.36.2 triton-3.6.0 xxhash-3.6.0
Collecting torch==2.9.1
  Using cached torch-2.9.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (4.12.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2024.5.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2.27.5)

Collecting nvidia-nvshmem-cu12==3.3.20 (from torch==2.9.1)
  Using cached nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.13.1.3)
Collecting triton==3.5.1 (from torch==2.9.1)
  Using cached triton-3.5.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch==2.9.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.9.1) (2.1.5)
Using cached torch-2.9.1-cp310-cp310-manylinux_2_28_x86_64.whl (899.8 MB)
Using cached nvidia_nvshmem_cu12-3.3.20-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (124.7 MB)
Using cached triton-3.5.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (170.3 MB)
Installing collected packages: triton, nvidia-nvshmem-cu12, torch
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: nvidia-nvshmem-cu12
    Found existing installation: nvidia-nvshmem-cu12 3.4.5
    Uninstalling nvidia-nvshmem-cu12-3.4.5:
      Successfully uninstalled nvidia-nvshmem-cu12-3.4.5
  Attempting uninstall: torch
    Found existing installation: torch 2.10.0
    Uninstalling torch-2.10.0:
      Successfully uninstalled torch-2.10.0
Successfully installed nvidia-nvshmem-cu12-3.3.20 torch-2.9.1 triton-3.5.1
Collecting ipywidgets==8.1.7
  Using cached ipywidgets-8.1.7-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (8.21.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (5.9.0)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets==8.1.7)
  Using cached widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets==8.1.7)
  Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.19.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (3.0.46)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (2.18.0)
Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.6.3)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (1.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (4.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.1.7) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.1.7) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.1.7) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (2.4.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (1.16.0)
Using cached ipywidgets-8.1.7-py3-none-any.whl (139 kB)
Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
Using cached widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets
Successfully installed ipywidgets-8.1.7 jupyterlab_widgets-3.0.16 widgetsnbextension-4.0.15
Collecting python-dotenv==1.2.1
  Using cached python_dotenv-1.2.1-py3-none-any.whl.metadata (25 kB)
Collecting pickleshare==0.7.5
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl.metadata (1.5 kB)
Using cached python_dotenv-1.2.1-py3-none-any.whl (21 kB)
Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Installing collected packages: pickleshare, python-dotenv
Successfully installed pickleshare-0.7.5 python-dotenv-1.2.1

In [15]:
from dotenv import load_dotenv
import os

load_dotenv("../../.env",override=True)

HF_TOKEN = os.getenv("HF_TOKEN")

#print("HF_TOKEN: ", HF_TOKEN)

 # source: https://huggingface.co/docs/transformers/v4.28.1/tasks/summarization
from huggingface_hub import login
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

Token has not been saved to git credential helper.
Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

# Continued Pre-training

In [ ]:
# from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

# Load domain-specific text (replace with your own corpus)
lang = "csb-pol-sent"
train_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json/data/{lang}_trn.tsv"
eval_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json/data/{lang}_dev.tsv"
dataset = load_dataset("csv", delimiter="\t",column_names=["input","labels"],data_files={"train": train_path,"validation": eval_path},quoting=3) # disable quote parsing


# Tokenizer
def preprocess_function(examples):
    # inputs = [prefix + doc for doc in examples["text"]]
    inputs = examples["input"]
    model_inputs = tokenizer(inputs)

    labels = tokenizer(text_target=examples["labels"],padding=True) # same length irrelevant here, so no truncation or padding

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
tokenized_dataset = dataset.map(preprocess_function, batched=True)

# Load pre-trained model
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, return_tensors="pt")
# Training arguments
training_args = TrainingArguments (
    output_dir="./byt5_small/"+lang+"-8epochs",
    overwrite_output_dir=True,
    num_train_epochs=8,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    evaluation_strategy = "epoch",
    #predict_with_generate=True,
   # save_steps=10_000,
    save_total_limit=3,
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
)

# Pretrain the model
trainer.train()
trainer.push_to_hub()

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

# Fine-tuning small pre-trained ByT5 model using dataset

In [10]:
LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"]
LANGS = LANGS[-2:]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul-language-code","mul-language-word"]
LANGS = ["mul-language-code"]
LANGS = ["pol"]
#LANGS = ["slavic-family"]
#LANGS = ["slk"] # ces, slk, dsb
CHECKPOINT = "livles/csb-sent-6epochs"
CHECKPOINT = "google/byt5-small"


PATH_JSON_DATA = "../preprocessing/preprocessing_to_json_or_tsv/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang.split("-")[0] + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # -

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    checkpoint = CHECKPOINT
    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/"+lang,
        evaluation_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=4,
        predict_with_generate=True,
        # save_strategy="epoch",
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        # load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,   
    )

    trainer.train()
    trainer.push_to_hub()

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

{'input': 'Inflect zacny | ADJ;ACC(SG,FEM)', 'target': 'zacną'}

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[125, 100, 102, 113, 199, 136, 1]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

# Fine-Tuning with more epochs

In [8]:
!rm -rf /dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5/byt5_small/*
LANGS = ["5lang-sample"]
#LANGS = ["slavic-family"]

PATH_JSON_DATA = "../preprocessing/preprocessing_to_json/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # 

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/"+lang+"_13epochs",
        eval_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=13,
        predict_with_generate=True,
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        save_strategy="epoch",
        load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification,
        greater_is_better=False,
        metric_for_best_model="eval_loss"
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,
        # compute_metrics=compute_metrics,
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Navajo: Inflect náʼáłkad | V;IND;PFV;NOM(1,GRPL)', 'target': 'ńdaʼiilkad'}
DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[200, 135, 103, 100, 205, 191, 108, 108, 111, 110, 100, 103, 1]

/tmp/ipykernel_3401446/2533773261.py:79: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

# Inference

In [ ]:
# SETTINGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"] + ["mul_2","ote","pol","amh"] + ["mul-language-code","mul-language-word"]
SETTINGS = ["mul"]
SETTINGS = ["5lang-sample"]
BASE_TEST_LANGUAGES_OF_SETTING = {"slavic":["csb"],"slavic-word":["csb"],"slavic-family":["pol","ces","csb","dsb","slk"],"5lang-sample":["deu","nav","klr","amh","grc"],"5lang-sample_16epochs":["amh"],
                                 "sme-15ksamples":["sme"],"sme-20ksamples":["sme"],"klr-15ksamples":["klr"],"klr-20ksamples":["klr"],"slavic-distant-word": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],"slavic-distant-word-or-family": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],
                                  "csb-pol":["csb","pol"], "csb-pol-sent-pol": ["csb", "pol"], "csb-pol-sent-6epochs-pol": ["csb", "pol"],
                                  "csb-sent-6epochs-pol": ["csb", "pol"], "dsb":["dsb"],"slk":["slk"],"ces":["ces"],"grc":["grc"],"sme":["sme"],"klr":["klr"],"nav":["nav"],
                                  "mul-language-word":["klr"],"pol":["csb"],"amh":["amh"],"mul_2":["sme","klr","grc"]
                                 }
CODES = {"slavic": [""],"slavic-word":["-lang-word"],"slavic-family":["-family","-lang-word","-word-or-family"],"5lang-sample":["-lang-word"],"5lang-sample_16epochs":["-lang-word"],"5lang-sample_13epochs":["-lang-word"],"sme-15ksamples":[""],"sme-20ksamples":[""],"klr-15ksamples":[""],"klr-20ksamples":[""],"slavic-distant-word":["-lang-word"],"slavic-distant-word-or-family":["-lang-word"],"csb-pol":[""],"csb-pol-sent-pol":[""],"csb-pol-sent-6epochs-pol": [""],"csb-sent-6epochs-pol": [""],"ces":[""],"slk":[""],"dsb":[""],"grc":[""],"sme":[""],"klr":[""],
        "mul-language-word":["-lang-word"],"nav":[""],"pol":[""],"amh":[""],"mul_2":[""],"csb-pol":[""]}
SETTINGS = ["slavic","slavic-word"]
SETTINGS = ["sme-15ksamples","sme-20ksamples","klr-15ksamples","klr-20ksamples","5lang-sample_16epochs"]
SETTINGS = ["slavic-distant-word-or-family"]
SETTINGS = ["csb-sent-6epochs-pol"]
SETTINGS = ["slavic"]
SETTINGS = ["pol"]
#SETTINGS = ["mul-language-word"]
#TEST_LANGS_OLD = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] 
#TEST_LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] + ["ote","pol","amh","csb"]
#lang5_LANGS = ["deu","nav","klr","amh","grc"]
#lang_code = ""
ERROR_ANALYSIS_PATH = "/dss/dsshome1/03/ge87wod2/morphological-inflection/error_analysis_lucy/byt5"
for lang_setting in SETTINGS:
    test_langs = BASE_TEST_LANGUAGES_OF_SETTING[lang_setting]
    #if lang_setting == "mul": LANG_CODES = ["-language-word","-language-code",""] # test with no language code/word too
    #else: LANG_CODES = [""]
    #for lang_code in LANG_CODES:
        #if lang_setting in ( "deu_eng", "mul") and lang_code == "": test_langs = TEST_LANGS_OLD
        #elif lang_setting in ["mul_2","mul"]: test_langs = TEST_LANGS # test multilingual model on all languages it was trained on + Kashubian
        #elif lang_setting == "5lang-sample": test_langs = lang5_LANGS
        #elif lang_setting == "pol": test_langs = ["pol","csb"] # test Polish model on Kashubian also
        #else: 
    for lang_code in CODES[lang_setting]:
        for test_lang in test_langs:
            import torch
            from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
            PRETRAINED_MODEL = "google/byt5-small"
            FINETUNED_MODEL ="livles/"+lang_setting
            #FINETUNED_MODEL ="./byt5_small/"+lang_setting + lang_code
            MODEL = FINETUNED_MODEL
            print(MODEL)
            tokenizer = AutoTokenizer.from_pretrained(
                FINETUNED_MODEL,
            )
            model = AutoModelForSeq2SeqLM.from_pretrained(
                FINETUNED_MODEL,
            torch_dtype=torch.float16,
            device_map="auto"
            )
            from datasets import load_dataset
            OUT_DIR = "output_byt5_small/" + lang_setting + "/" 
            PATH_TO_JSON_TEST_FILE = "../preprocessing/preprocessing_to_json_or_tsv/data/" + test_lang + lang_code+ "_tst.json"
            #ERROR_ANALYSIS_PATH = "/dss/dsshome1/03/ge87wod2/morphological-inflection/error_analysis_lucy/byt5/" + lang_setting + "/" + test_lang + lang_code + ".errors"
            print("test file: ",PATH_TO_JSON_TEST_FILE)
            PATH_TO_ORIG_TEST_FILE = "../task-data/" + test_lang + ".tst"
            from pathlib import Path
            Path(OUT_DIR).mkdir(parents=True, exist_ok=True)
            with open (OUT_DIR + test_lang + lang_code + "_byt5-small.out","w") as out_file, open (PATH_TO_ORIG_TEST_FILE, "r") as test_file: #, open (ERROR_ANALYSIS_PATH, "w") as error_file
                dataset = load_dataset("json",data_files={"test":PATH_TO_JSON_TEST_FILE})
                covered_test_lines = dataset["test"]["input"]
                LEN = len(covered_test_lines)
                COUNTER = 0

                # preds = map (generate,covered_test_lines)
                for line in covered_test_lines:
                    input_ids = tokenizer(line, return_tensors="pt").to(model.device)
                    output = model.generate(
                        **input_ids,
                        max_new_tokens=50,
                        num_beams=4,
                        #early_stopping=True
                    )
                    output_string = (tokenizer.decode(output[0], skip_special_tokens=True))
                    ref_line = test_file.readline()
                    lemma, features, ref = ref_line.strip().split("\t")

                    # evaluate
                    if (ref == output_string):
                        COUNTER += 1
                        print(ref,output_string)
                    else:
                        print("ref:",ref,"pred:",output_string)
                     #   error_file.write("ref\t"+ref_line+"\n")
                      #  error_file.write("byt5\t"+line+"\n\n")
                       # error_file.flush()
                    # write
                    out_file.write(lemma + "\t" +features+ "\t" + output_string + "\n")
                    out_file.flush()

                accuracy = COUNTER / LEN
                out_file.write("accuracy:"+ str(accuracy)+"\n")
                print(accuracy)

livles/pol

tokenizer_config.json: 0.00B [00:00, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

config.json:   0%|          | 0.00/837 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/142 [00:00<?, ?B/s]

test file:  ../preprocessing/preprocessing_to_json_or_tsv/data/csb_tst.json
ref: narzãdzacze pred: narzãdzôcze
ref: narzãdzaczom pred: narzãdzôczom
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczama pred: narzãdzôczami
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczowi pred: narzãdzôczowi
ref: narzãdzacza pred: narzãdzôczu
ref: narzãdzaczach pred: narzãdzôczach
ref: narzãdzaczów pred: narzãdzôczów
ref: narzãdzaczã pred: narzãdzôczem
ref: narzãdzacze pred: narzãdzôcze
ref: narzãdzacza pred: narzãdzôcz
narzãdzôcz narzãdzôcz
ref: narzãdzacze pred: narzãdzôczy
ref: Jastrë pred: Jastrów
Jastrach Jastrach
ref: Jastróm pred: Jastrom
Jastrów Jastrów
ref: Jastrama pred: Jastrów
ref: Jastrë pred: Jastrów
ref: Jastrë pred: Jastrów
ref: pòniedzałczi pred: pòniedzôłki
ref: pòniedzałkóm pred: pòniedzôłkom
ref: pòniedzałkù pred: pòniedzôłku
ref: pòniedzałkama pred: pòniedzôłkami
ref: pòniedzałkù pred: pòniedzôłku
ref: poniedzałkòwi pred: pòniedzôłkowi
ref: pòniedzałkù pred: pòniedzôłku
ref: pòniedzałkach pred: pòniedzôłkach
ref: pòniedzałków pred: pòniedzôłków
ref: pòniedzałkã pred: pòniedzôłkiem
ref: pòniedzałczi pred: pòniedzôłki
pòniedzôłk pòniedzôłk
pòniedzôłk pòniedzôłk
ref: pòniedzałczi pred: pòniedzôłki
ref: pùjczi pred: pùjki
pùjkom pùjkom
ref: pùjkù pred: pùjku
ref: pùjkama pred: pùjkami
ref: pùjkù pred: pùjku
ref: pùjkòwi pred: pùjkowi
ref: pùjka pred: pùjku
pùjkach pùjkach
pùjków pùjków
ref: pùjkã pred: pùjkem
ref: pùjczi pred: pùjki
ref: pùjka pred: pùjk
pùjk pùjk
ref: pùjczi pred: pùjki
ref: môlniczi pred: môlniki
ref: môlnikòm pred: môlnikom
ref: môlnikù pred: môlniku
ref: môlnikama pred: môlnikami
ref: môlnikù pred: môlniku
ref: môlnikòwi pred: môlnikowi
ref: môlnika pred: môlniku
môlnikach môlnikach
môlników môlników
ref: môlnikã pred: môlnikem
ref: môlniczi pred: môlniki
môlnik môlnik
môlnik môlnik
ref: môlniczi pred: môlniki
ref: wòłiwaczë pred: wòłiwocze
ref: wòłiwaczom pred: wòłiwoczom
ref: wòłiwaczu pred: wòłiwoczu
ref: wòłiwaczama pred: wòłiwoczami
ref: wòłiwaczu pred: wòłiwoczu
ref: wòłiwaczowi pred: wòłiwoczowi
ref: wòłiwacza pred: wòłiwoczu
ref: wòłiwaczach pred: wòłiwoczach
ref: wòłiwaczów pred: wòłiwoczów
ref: wòłiwaczã pred: wòłiwoczem
ref: wòłiwaczë pred: wòłiwocze
ref: wòłiwacza pred: wòłiwocz
ref: wòłiwôcz pred: wòłiwocz
ref: wòłiwaczë pred: wòłiwoczy
ref: łżëkwiôtë pred: łżëkwioty
ref: łżëkwiôtom pred: łżëkwiotom
ref: łżëkwiôce pred: łżëkwiotu
ref: łżëkwiôtama pred: łżëkwiotami
ref: łżëkwiôce pred: łżëkwiotu
ref: łżëkwiôtowi pred: łżëkwiotowi
ref: łżëkwiôta pred: łżëkwiotu
ref: łżëkwiôtach pred: łżëkwiotach
ref: łżëkwiôtów pred: łżëkwiotów
ref: łżëkwiôtã pred: łżëkwiotem
ref: łżëkwiôtë pred: łżëkwioty
ref: łżëkwiôta pred: łżëkwiot
ref: łżëkwiôt pred: łżëkwiot
ref: łżëkwiôtë pred: łżëkwioty
ref: lëstopadniczi pred: lëstopadniki
ref: lëstopadnikòm pred: lëstopadnikom
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikama pred: lëstopadnikami
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikòwi pred: lëstopadnikowi
ref: lëstopadnika pred: lëstopadniku
lëstopadnikach lëstopadnikach
lëstopadników lëstopadników
ref: lëstopadnikã pred: lëstopadnikiem
ref: lëstopadniczi pred: lëstopadniki
ref: lëstopadnika pred: lëstopadnik
lëstopadnik lëstopadnik
ref: lëstopadniczi pred: lëstopadniki
ref: sobòtë pred: sobòty
ref: sobòtóm pred: sobotom
sobòto sobòto
ref: sobòtama pred: sobotami
ref: sobòce pred: sobotzie
ref: sobòce pred: sobòtowi
ref: sobòtë pred: soboty
ref: sobòtach pred: sobotach
ref: sobòtów pred: sobót
ref: sobòtã pred: sobòtą
ref: sobòtë pred: sobòty
ref: sobòtã pred: sobòtę
sobòta sobòta
ref: sobòtë pred: sobòty
ref: kònie pred: kóń
ref: kòniom pred: kóńom
ref: kòniu pred: kóń
ref: kòniama pred: kóńami
ref: kòniu pred: kóńu
ref: kòniowi pred: kóńowi
ref: kònia pred: kóńa
ref: kòniach pred: kóńach
ref: kòni pred: kóń
ref: kòniã pred: kóńem
ref: kònie pred: kóń
ref: kònia pred: kóń
kóń kóń
ref: kònie pred: kóń
ref: nazéwacze pred: nazéwôcze
ref: nazéwaczom pred: nazéwôczom
ref: nazéwaczu pred: nazéwôczu
ref: nazéwaczama pred: nazéwôczami
ref: nazéwaczu pred: nazéwoczu
ref: nazéwaczowi pred: nazéwoczowi
ref: nazéwacza pred: nazéwoczu
ref: nazéwaczach pred: nazéwôczach
ref: nazéwaczów pred: nazéwôczów
ref: nazéwaczã pred: nazéwoczem
ref: nazéwacze pred: nazéwôcze
ref: nazéwacza pred: nazéwocz
ref: nazéwôcz pred: nazéwocz
ref: nazéwacze pred: nazéwôczy
ref: piątczi pred: piątki
ref: piątkóm pred: piątkom
ref: piątkù pred: piątku
ref: piątkama pred: piątkami
ref: piątkù pred: piątku
ref: piątkòwi pred: piątkowi
ref: piątkù pred: piątka
piątkach piątkach
piątków piątków
ref: piątkã pred: piątkiem
ref: piątczi pred: piątki
piątk piątk
piątk piątk
ref: piątczi pred: piątki
ref: rënczi pred: rënki
ref: rënkóm pred: rënkom
ref: stolem pred: rënku
ref: rënkama pred: rënkami
ref: rënkù pred: rënku
ref: rënkòwi pred: rënkowi
ref: rënkù pred: rënku
rënkach rënkach
rënków rënków
ref: rënkã pred: rënkem
ref: rënczi pred: rënki
rënk rënk
rënk rënk
ref: rënczi pred: rënki
ref: wtórczi pred: wtórki
ref: wtórkòm pred: wtórkom
ref: wtórkù pred: wtórku
ref: wtórkama pred: wtórkami
ref: wtórkù pred: wtórku
ref: wtórkòwi pred: wtórkowi
wtórka wtórka
wtórkach wtórkach
wtórków wtórków
ref: wtórkã pred: wtórkem
ref: wtórczi pred: wtórki
wtórk wtórk
wtórk wtórk
ref: wtórczi pred: wtórki
ref: winowacze pred: winowôcze
ref: winowaczom pred: winowoczom
ref: winowaczu pred: winowôczu
ref: winowaczama pred: winowôczami
ref: winowaczu pred: winowôczu
ref: winowaczowi pred: winowôczowi
ref: winowacza pred: winowôczu
ref: winowaczach pred: winowôczach
ref: winowaczów pred: winowôczów
ref: winowaczã pred: winowôczem
ref: winowacze pred: winowôcze
ref: winowacza pred: winowôcz
winowôcz winowôcz
ref: winowacze pred: winowôczy
ref: òjcowie pred: òjcy
ref: òjcóm pred: òjcom
ref: òjcze pred: òjcu
ref: òjcama pred: òjcami
ref: òjcu pred: òjcie
ref: òjcu pred: òjcowi
ref: òjca pred: òjcu
òjcach òjcach
òjców òjców
ref: òjcã pred: òjcem
òjcem òjcem
ref: òjców pred: òjcy
ref: òjca pred: òjc
òjc òjc
ref: òjcowie pred: òjcy
ref: latawiska pred: latawiski
ref: latawiskóm pred: latawiskom
ref: latawiskù pred: latawisko
ref: latawiskama pred: latawiskami
ref: latawiskù pred: latawisku
ref: latawiskù pred: latawiskowi
latawiska latawiska
latawiskach latawiskach
latawisków latawisków
ref: latawiskã pred: latawiskom
ref: latawiska pred: latawisków
ref: latawiskò pred: latawisko
ref: latawiskò pred: latawisko
ref: latawiska pred: latawisków
ref: Jastra pred: Jastry
Jastrach Jastrach
ref: Jastróm pred: Jastrom
Jastrów Jastrów
ref: Jastrama pred: Jastry
ref: Jastra pred: Jastry
ref: Jastra pred: Jastry
ref: czerwińce pred: czerwińcy
czerwińcom czerwińcom
czerwińcu czerwińcu
ref: czerwińcama pred: czerwińcami
czerwińcu czerwińcu
czerwińcowi czerwińcowi
czerwińca czerwińca
czerwińcach czerwińcach
czerwińców czerwińców
ref: czerwińcã pred: czerwińcem
czerwińce czerwińce
ref: czerwińca pred: czerwińc
czerwińc czerwińc
ref: czerwińc pred: czerwińcy
ref: rujanë pred: rujany
rujanom rujanom
rujanie rujanie
ref: rujanama pred: rujanami
rujanie rujanie
rujanowi rujanowi
ref: rujana pred: rujanu
rujanach rujanach
rujanów rujanów
ref: rujanã pred: rujanem
ref: rujanë pred: rujany
ref: rujana pred: rujan
rujan rujan
ref: rujanë pred: rujany
ref: dôwacze pred: dôwôcze
ref: dôwaczom pred: dôwôczom
ref: dôwaczu pred: dôwôczu
ref: dôwaczama pred: dôwôczami
ref: dôwaczu pred: dôwôczu
ref: dôwaczowi pred: dôwôczowi
ref: dôwôcza pred: dôwôczu
ref: dôwaczach pred: dôwôczach
ref: dôwaczów pred: dôwôczów
ref: dôwaczã pred: dôwôczem
ref: dôwacze pred: dôwôcze
ref: dôwacza pred: dôwôcz
dôwôcz dôwôcz
ref: dôwacze pred: dôwôczy
ref: serca pred: serce
ref: sercóm pred: sercom
ref: serce pred: serco
ref: sercama pred: sercami
ref: sercu pred: sercie
ref: serce pred: sercie
ref: sercu pred: sercowi
serca serca
sercach sercach
serców serców
ref: serc pred: serców
ref: sercã pred: sercą
ref: sercem pred: sercą
ref: serca pred: serce
serce serce
serce serce
ref: serca pred: serce
ref: lëpince pred: lëpincy
lëpincom lëpincom
lëpincu lëpincu
ref: lëpincama pred: lëpincami
ref: lëpincu pred: lëpincie
lëpincowi lëpincowi
ref: lëpinca pred: lëpincu
lëpincach lëpincach
lëpinców lëpinców
ref: lëpincã pred: lëpincem

lëpince lëpince
lëpinc lëpinc
lëpinc lëpinc
ref: lëpince pred: lëpincy
ref: séwniczi pred: séwniki
ref: séwnikòm pred: séwnikom
ref: séwnikù pred: séwniku
ref: séwnikama pred: séwnikami
ref: séwnikù pred: séwniku
ref: séwnikòwi pred: séwnikowi
ref: séwnika pred: séwniku
séwnikach séwnikach
séwników séwników
ref: séwnikã pred: séwnikem
ref: séwniczi pred: séwniki
ref: séwnika pred: séwnik
séwnik séwnik
ref: séwniczi pred: séwniki
ref: zélniczi pred: zélniki
ref: zélnikòm pred: zélnikom
ref: zélnikù pred: zélniku
ref: zélnikama pred: zélnikami
ref: zélnikù pred: zélniku
ref: zélnikòwi pred: zélnikowi
zélnika zélnika
zélnikach zélnikach
zélników zélników
ref: zélnikã pred: zélnikem
ref: zélniczi pred: zélniki
ref: zélnika pred: zélnik
zélnik zélnik
ref: zélniczi pred: zélniki
ref: stëczniczi pred: stëczniki
ref: stëcznikòm pred: stëcznikom
ref: stëcznikù pred: stëczniku
ref: stëcznikama pred: stëcznikami
ref: stëcznikù pred: stëczniku
ref: stëcznikòwi pred: stëcznikowi
stëcznika stëcznika
stëcznikach stëcznikach
stëczników stëczników
ref: stëcznikã pred: stëcznikiem
ref: stëczniczi pred: stëczniki
ref: stëcznika pred: stëcznik
stëcznik stëcznik
ref: stëczniczi pred: stëczniki
ref: strzodë pred: strzody
ref: strzodóm pred: strzodom
strzodo strzodo
ref: strzodama pred: strzodami
ref: strzodze pred: strzodzie
ref: strzodze pred: strzodzie
ref: strzodë pred: strzody
strzodach strzodach
strzodów strzodów
ref: strzodã pred: strzodą
ref: strzodë pred: strzody
ref: strzodã pred: strzodę
strzoda strzoda
ref: strzodë pred: strzody
ref: maje pred: moje
ref: majom pred: mojom
ref: maju pred: moju
ref: majima pred: mojami
ref: maju pred: moju
ref: majowi pred: mojowi
ref: maja pred: moju
ref: majach pred: mojach
ref: majów pred: mojów
ref: majã pred: mojem
ref: maje pred: moje
ref: môj pred: moj
ref: môj pred: moj
ref: maje pred: moje
ref: strumianniczi pred: strumianniki
ref: strumiannikòm pred: strumiannikom
ref: strumiannikù pred: strumianniku
ref: strumiannikama pred: strumiannikami
ref: strumiannikù pred: strumianniku
ref: strumiannikòwi pred: strumiannikowi
ref: strumiannika pred: strumianniku
strumiannikach strumiannikach
strumianników strumianników
ref: strumiannikã pred: strumiannikiem
ref: strumianniczi pred: strumianniki
strumiannik strumiannik
strumiannik strumiannik
ref: strumianniczi pred: strumianniki
ref: tidzénie pred: tidzenie
ref: tidzénióm pred: tidzeniom
ref: tidzéniu pred: tidzenie
ref: tidzénama pred: tidzeniami
ref: tidzéniu pred: tidzeniu
ref: tidzéniowi pred: tidzeniowi
ref: tidzénia pred: tidzenia
ref: tidzénach pred: tidzeniach
ref: tidzéniów pred: tidzów
ref: tidzénã pred: tidzeniem
ref: tidzénie pred: tidzenie
ref: tidzéń pred: tidzeni
ref: tidzéń pred: tidzeni
ref: tidzénie pred: tidzenie
ref: czwôrtczi pred: czwôrtki
ref: czwôrtkóm pred: czwôrtkom
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkama pred: czwôrtkami
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkòwi pred: czwôrtkowi
ref: czwôrtkù pred: czwôrtka
czwôrtkach czwôrtkach
czwôrtków czwôrtków
ref: czwôrtkã pred: czwôrtkiem
ref: czwôrtczi pred: czwôrtki
czwôrtk czwôrtk
czwôrtk czwôrtk
ref: czwôrtczi pred: czwôrtki
ref: kòtë pred: kòty
kòtom kòtom
ref: kòce pred: kòtu
ref: kòtama pred: kòtami
ref: kòce pred: kòtu
kòtowi kòtowi
ref: kòtu pred: kòtowi
ref: kòta pred: kòtu
kòtach kòtach
kòtów kòtów
ref: kòtã pred: kòtem
ref: kòtë pred: kòty
ref: kòta pred: kòt
kòt kòt
ref: kòtë pred: kòty
ref: gromiczniczi pred: gromiczniki
ref: gromicznikòm pred: gromicznikom
ref: gromicznikù pred: gromiczniku
ref: gromicznikama pred: gromicznikami
ref: gromicznikù pred: gromiczniku
ref: gromicznikòwi pred: gromicznikowi
gromicznika gromicznika
gromicznikach gromicznikach
gromiczników gromiczników
ref: gromicznikã pred: gromicznikiem
ref: gromiczniczi pred: gromiczniki
ref: gromicznika pred: gromicznik
gromicznik gromicznik
ref: gromiczniczi pred: gromiczniki
rodzôcze rodzôcze
rodzôczom rodzôczom
rodzôczu rodzôczu
ref: rodzôczama pred: rodzôczami
rodzôczu rodzôczu
rodzôczowi rodzôczowi
ref: rodzôcza pred: rodzôczu
rodzôczach rodzôczach
rodzôczów rodzôczów
ref: rodzôczã pred: rodzôczem
rodzôcze rodzôcze
ref: rodzôcza pred: rodzôcz
rodzôcz rodzôcz
ref: rodzôcze pred: rodzôczy
niedzele niedzele
ref: niedzelóm pred: niedzelom
niedzelo niedzelo
ref: niedzelama pred: niedzelami
niedzeli niedzeli
ref: niedzeli pred: niedzelowi
ref: niedzeli pred: niedzely
niedzelach niedzelach
ref: niedzelów pred: niedzel
ref: niedzelã pred: niedzelą
niedzele niedzele
ref: niedzelã pred: niedzelę
niedzela niedzela
niedzele niedzele
ref: gòdniczi pred: gòdniki
ref: gòdnikòm pred: gòdnikom
ref: gòdnikù pred: gòdniku
ref: gòdnikama pred: gòdnikami
ref: gòdnikù pred: gòdniku
ref: gòdnikòwi pred: gòdnikowi
ref: gòdnika pred: gòdniku
gòdnikach gòdnikach
gòdników gòdników
ref: gòdnikã pred: gòdnikem
ref: gòdniczi pred: gòdniki
ref: gòdnika pred: gòdnik
gòdnik gòdnik
ref: gòdniczi pred: gòdniki
ref: stolemë pred: stolemy
ref: stolemóm pred: stolemom
ref: stolem pred: stolemu
ref: stolemama pred: stolemami
stolemie stolemie
ref: stolemòwi pred: stolemowi
ref: stolema pred: stolemu
stolemach stolemach
stolemów stolemów
ref: stolemã pred: stolemem
ref: stolemów pred: stolemy
ref: stolema pred: stolem
stolem stolem
ref: stolemë pred: stolemy
0.24950884086444008