# Setup

In [6]:
%cd /dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5/
import sys
print(sys.version)

/dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

In [2]:
!pip uninstall transformers  accelerate torch -y
!rm -rf /usr/local/lib/python3.10/dist-packages/-andas*
!pip install torch==2.9.1  datasets==2.19.2  tiktoken==0.12.0 pandas==2.2.2 numpy==1.23.5 pyarrow==16.1.0
!pip install transformers==4.36.0
!pip install accelerate==0.28.0
!pip install ipywidgets==8.1.8
!pip install python-dotenv==8.1.8 pickleshare==0.7.5

Found existing installation: transformers 4.36.0
Uninstalling transformers-4.36.0:
  Successfully uninstalled transformers-4.36.0
Found existing installation: accelerate 0.28.0
Uninstalling accelerate-0.28.0:
  Successfully uninstalled accelerate-0.28.0
Found existing installation: torch 2.9.1
Uninstalling torch-2.9.1:
  Successfully uninstalled torch-2.9.1
Collecting torch==2.9.1
  Using cached torch-2.9.1-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (30 kB)
Requirement already satisfied: datasets==2.19.2 in /usr/local/lib/python3.10/dist-packages (2.19.2)
Requirement already satisfied: tiktoken==0.12.0 in /usr/local/lib/python3.10/dist-packages (0.12.0)
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy==1.23.5 in /usr/local/lib/python3.10/dist-packages (1.23.5)
Requirement already satisfied: pyarrow==16.1.0 in /usr/local/lib/python3.10/dist-packages (16.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2024.3.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.5.1)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (0.7)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (0.3.8)
Requirement already satisfied: requests>=2.32.1 in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (0.70.16)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (3.9.5)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets==2.19.2) (6.0.1)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.10/dist-packages (from tiktoken==0.12.0) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2024.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.19.2) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.19.2) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.19.2) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.19.2) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.19.2) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets==2.19.2) (4.0.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.21.2->datasets==2.19.2) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.1->datasets==2.19.2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.1->datasets==2.19.2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.1->datasets==2.19.2) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.1->datasets==2.19.2) (2024.6.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch==2.9.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.9.1) (2.1.5)
Using cached torch-2.9.1-cp310-cp310-manylinux_2_28_x86_64.whl (899.8 MB)
Installing collected packages: torch
Successfully installed torch-2.9.1
Collecting transformers==4.36.0
  Using cached transformers-4.36.0-py3-none-any.whl.metadata (126 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (2.32.3)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (0.15.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.0) (4.67.1)

Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.0) (2024.3.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.0) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.0) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.0) (2024.6.2)
Using cached transformers-4.36.0-py3-none-any.whl (8.2 MB)
Installing collected packages: transformers
Successfully installed transformers-4.36.0
Collecting accelerate==0.28.0
  Using cached accelerate-0.28.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.28.0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.28.0) (24.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate==0.28.0) (5.9.8)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate==0.28.0) (6.0.1)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.28.0) (2.9.1)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (from accelerate==0.28.0) (0.36.0)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.28.0) (0.7.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (2024.3.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.28.0) (3.5.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate==0.28.0) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate==0.28.0) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate==0.28.0) (1.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.28.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate==0.28.0) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.28.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.28.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.28.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate==0.28.0) (2024.6.2)
Using cached accelerate-0.28.0-py3-none-any.whl (290 kB)
Installing collected packages: accelerate
Successfully installed accelerate-0.28.0
Requirement already satisfied: ipywidgets==8.1.8 in /usr/local/lib/python3.10/dist-packages (8.1.8)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (8.21.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (5.9.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (3.0.16)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (0.19.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (3.0.46)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (2.18.0)
Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (0.6.3)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (1.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (4.7.0)

Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.1.8) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.1.8) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.1.8) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.8) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.8) (2.4.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.8) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets==8.1.8) (1.16.0)
ERROR: Could not find a version that satisfies the requirement python-dotenv==8.1.8 (from versions: 0.1.0, 0.1.2, 0.1.3, 0.1.5, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.21.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1)
ERROR: No matching distribution found for python-dotenv==8.1.8

# Pre-training
with 10k sentences in Kashubian

In [11]:
# source: https://corpora.uni-leipzig.de/en?corpusId=csb_wikipedia_2021
# source: https://huggingface.co/docs/transformers/v4.57.1/en/model_doc/t5#transformers.T5Config
sentences_path = "/dss/dsshome1/03/ge87wod2/morphological-inflection/data/leipzig-corpera-collection/csb_wikipedia_2021_10K/" + "csb_wikipedia_2021_10K-sentences.txt"
import random
import math
with open (sentences_path,"r") as in_file:
   
    lines = in_file.readlines()
    for i in range(math.floor((len(lines)-1)/16)):
        if i == 4: break
        print(i)
        inputs = []
        labels = []
        batch_lines = lines[i*16:min(i*16+16,len(lines))]
        for line in batch_lines:
            sentence = line.split("\t")[1] # cut out line number
            words = sentence.split(" ")
            end_index = len(words)-4
            mask_len = 3
            while (end_index < 1 and mask_len > 0 ):
                mask_len -= 1
                end_index += 1
            start_index = random.randint(1,end_index) # mask 3 words: start mask between second and fourth last word
            input_sentence = words[:start_index] + ["<extra_id_0>"] + words[start_index+mask_len:]
            label_sentence = ["<extra_id_0>"]+words[start_index:start_index+mask_len]+["<extra_id_1>"]
            input_sentence = " ".join(input_sentence)
            label = " ".join(label_sentence)
            inputs.append(input_sentence)
            labels.append(label)
            from transformers import AutoTokenizer, T5ForConditionalGeneration, AutoModelForSeq2SeqLM
            tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
            model = T5ForConditionalGeneration.from_pretrained("google/byt5-small")

            # training
            input_ids = tokenizer(inputs, return_tensors="pt",padding=True).input_ids
            labels_batch = tokenizer(labels, return_tensors="pt",padding=True).input_ids
            outputs = model(input_ids=input_ids, labels=labels_batch)
            loss = outputs.loss
            logits = outputs.logits
print(inputs[0],labels[0])

# inference
input_ids = tokenizer(
    "The <extra_id_0> walks in <extra_id_1> park", return_tensors="pt"
).input_ids  # Batch size 1
outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
# studies have shown that owning a dog is good for you.

0

NameError: name 'model' is not defined

In [19]:
input_ids = tokenizer("The dog chases a ball in the park.").input_ids
masked_input = torch.tensor([input_ids[:8] + [258] + input_ids[14:21] + [257] + input_ids[28:]])
print(input_ids)
print(masked_input)
output = model.generate(masked_input, max_length=100)

[87, 107, 104, 35, 103, 114, 106, 35, 102, 107, 100, 118, 104, 118, 35, 100, 35, 101, 100, 111, 111, 35, 108, 113, 35, 119, 107, 104, 35, 115, 100, 117, 110, 49, 1]
tensor([[ 87, 107, 104,  35, 103, 114, 106,  35, 258,  35, 100,  35, 101, 100,
         111, 111, 257,  35, 115, 100, 117, 110,  49,   1]])

In [4]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

# Load domain-specific text (replace with your own corpus)
train_path = "/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json/data/csb-sent_trn.tsv"
eval_path = "/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json/data/csb-sent_dev.tsv"
dataset = load_dataset("csv", delimiter="\t",column_names=["input","labels"],data_files={"train": train_path,"validation": eval_path},quoting=3) # disable quote parsing


# Tokenizer
def preprocess_function(examples):
    # inputs = [prefix + doc for doc in examples["text"]]
    inputs = examples["input"]
    model_inputs = tokenizer(inputs)

    labels = tokenizer(text_target=examples["labels"],padding=True) # same length irrelevant here, so no truncation or padding

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
tokenized_dataset = dataset.map(preprocess_function, batched=True)

# Load pre-trained model
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, return_tensors="pt")
# Training arguments
training_args = TrainingArguments (
    output_dir="./byt5_small/csb-sent",
    overwrite_output_dir=True,
    num_train_epochs=4,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
   # save_steps=10_000,
   # save_total_limit=2,
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
)

# Pretrain the model
trainer.train()
trainer.push_to_hub()

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False)
  warnings.warn(

Checkpoint destination directory ./byt5_small/csb-sent/checkpoint-500 already exists and is non-empty.Saving will proceed but saved results may be invalid.
Checkpoint destination directory ./byt5_small/csb-sent/checkpoint-1000 already exists and is non-empty.Saving will proceed but saved results may be invalid.
Checkpoint destination directory ./byt5_small/csb-sent/checkpoint-1500 already exists and is non-empty.Saving will proceed but saved results may be invalid.

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/livles/csb-sent/commit/75d4965bede2367b21edd2395faddd5e6bd5a8c7', commit_message='End of training', commit_description='', oid='75d4965bede2367b21edd2395faddd5e6bd5a8c7', pr_url=None, repo_url=RepoUrl('https://huggingface.co/livles/csb-sent', endpoint='https://huggingface.co', repo_type='model', repo_id='livles/csb-sent'), pr_revision=None, pr_num=None)

In [5]:
import torch
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")

num_special_tokens = 3

input_ids = torch.tensor([list("Life is like a box of chocolates.".encode("utf-8"))]) + num_special_tokens
labels = torch.tensor([list("La vie est comme une boîte de chocolat.".encode("utf-8"))]) + num_special_tokens
loss = model(input_ids, labels=labels).loss
loss.item()

2.658773899078369

# Training small pre-trained ByT5 model using dataset

In [8]:
LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"]
LANGS = LANGS[-2:]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul-language-code","mul-language-word"]
LANGS = ["mul-language-code"]
LANGS = ["5lang-sample"]
#LANGS = ["slavic-family"]
LANGS = ["pol"]

PATH_JSON_DATA = "../preprocessing/preprocessing_to_json/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang.split("-")[0] + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # -

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    checkpoint = "livles/csb-sent"
    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/csb-"+lang,
        evaluation_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=4,
        predict_with_generate=True,
        # save_strategy="epoch",
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        # load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,
        # compute_metrics=compute_metrics,
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Inflect zacny | ADJ;ACC(SG,FEM)', 'target': 'zacną'}

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[125, 100, 102, 113, 199, 136, 1]

/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches']). Please pass an `accelerate.DataLoaderConfiguration` instead:
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False)
  warnings.warn(

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

# Train with more epochs

In [6]:
LANGS = ["5lang-sample"]
#LANGS = ["slavic-family"]



PATH_JSON_DATA = "../preprocessing/preprocessing_to_json/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # 

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/"+lang+"_13epochs",
        eval_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=13,
        predict_with_generate=True,
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        save_strategy="epoch",
        load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification,
        greater_is_better=False,
        metric_for_best_model="eval_loss"
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,
        # compute_metrics=compute_metrics,
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Navajo: Inflect náʼáłkad | V;IND;PFV;NOM(1,GRPL)', 'target': 'ńdaʼiilkad'}
DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[200, 135, 103, 100, 205, 191, 108, 108, 111, 110, 100, 103, 1]

/tmp/ipykernel_1244657/1895635383.py:78: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

# Testing models
+ [ ] TODO: finetune all slavic models and test them on the specific dataset
+ [ ] TODO: test 5lang-sample model on the dataset with prefixes

In [9]:
# SETTINGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"] + ["mul_2","ote","pol","amh"] + ["mul-language-code","mul-language-word"]
SETTINGS = ["mul"]
SETTINGS = ["5lang-sample"]
BASE_TEST_LANGUAGES_OF_SETTING = {"slavic":["pol","ces","csb","dsb","slk"],"slavic-word":["pol","ces","csb","dsb","slk"],"slavic-family":["pol","ces","csb","dsb","slk"],"5lang-sample":["deu","nav","klr","amh","grc"],"5lang-sample_16epochs":["deu","nav","klr","amh","grc"],
                                 "sme-15ksamples":["sme"],"sme-20ksamples":["sme"],"klr-15ksamples":["klr"],"klr-20ksamples":["klr"],"slavic-distant-word": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],"slavic-distant-word-or-family": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],
                                  "csb-pol":["csb","pol"]
                                 }
CODES = {"slavic": "","slavic-word":["-lang-word"],"slavic-family":["-family","-lang-word","-word-or-family"],"5lang-sample":["-lang-word"],"5lang-sample_16epochs":["-lang-word"],"5lang-sample_13epochs":["-lang-word"],"sme-15ksamples":[""],"sme-20ksamples":[""],"klr-15ksamples":[""],"klr-20ksamples":[""],"slavic-distant-word":["-lang-word"],"slavic-distant-word-or-family":["-lang-word"],"csb-pol":[""]}
SETTINGS = ["slavic","slavic-word"]
SETTINGS = ["sme-15ksamples","sme-20ksamples","klr-15ksamples","klr-20ksamples","5lang-sample_16epochs"]
SETTINGS = ["slavic-distant-word-or-family"]
SETTINGS = ["csb-pol"]

#TEST_LANGS_OLD = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] 
#TEST_LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] + ["ote","pol","amh","csb"]
#lang5_LANGS = ["deu","nav","klr","amh","grc"]
#lang_code = ""
for lang_setting in SETTINGS:
    test_langs = BASE_TEST_LANGUAGES_OF_SETTING[lang_setting]
    #if lang_setting == "mul": LANG_CODES = ["-language-word","-language-code",""] # test with no language code/word too
    #else: LANG_CODES = [""]
    #for lang_code in LANG_CODES:
        #if lang_setting in ( "deu_eng", "mul") and lang_code == "": test_langs = TEST_LANGS_OLD
        #elif lang_setting in ["mul_2","mul"]: test_langs = TEST_LANGS # test multilingual model on all languages it was trained on + Kashubian
        #elif lang_setting == "5lang-sample": test_langs = lang5_LANGS
        #elif lang_setting == "pol": test_langs = ["pol","csb"] # test Polish model on Kashubian also
        #else: 
    for lang_code in CODES[lang_setting]:
        for test_lang in test_langs:
            import torch
            from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
            PRETRAINED_MODEL = "google/byt5-small"
            FINETUNED_MODEL ="livles/"+lang_setting
            #FINETUNED_MODEL ="./byt5_small/"+lang_setting + lang_code
            MODEL = FINETUNED_MODEL
            print(MODEL)
            tokenizer = AutoTokenizer.from_pretrained(
                FINETUNED_MODEL,
            )
            model = AutoModelForSeq2SeqLM.from_pretrained(
                FINETUNED_MODEL,
            dtype=torch.float16,
            device_map="auto"
            )
            from datasets import load_dataset
            OUT_DIR = "output_byt5_small/" + lang_setting + "/" 
            PATH_TO_JSON_TEST_FILE = "../preprocessing/preprocessing_to_json/data/" + test_lang + lang_code+ "_tst.json"
            print("test file: ",PATH_TO_JSON_TEST_FILE)
            PATH_TO_ORIG_TEST_FILE = "../2023InflectionST/part1/data/" + test_lang + ".tst"
            from pathlib import Path
            Path(OUT_DIR).mkdir(parents=True, exist_ok=True)
            with open (OUT_DIR + test_lang + lang_code + "_byt5-small.out","w") as out_file, open (PATH_TO_ORIG_TEST_FILE, "r") as test_file:
                dataset = load_dataset("json",data_files={"test":PATH_TO_JSON_TEST_FILE})
                covered_test_lines = dataset["test"]["input"]
                LEN = len(covered_test_lines)
                COUNTER = 0

                # preds = map (generate,covered_test_lines)
                for line in covered_test_lines:
                    input_ids = tokenizer(line, return_tensors="pt").to(model.device)
                    output = model.generate(
                        **input_ids,
                        max_new_tokens=50,
                        num_beams=4,
                        #early_stopping=True
                    )
                    output_string = (tokenizer.decode(output[0], skip_special_tokens=True))
                    lemma, features, ref = test_file.readline().strip().split("\t")

                    # evaluate
                    if (ref == output_string):
                        COUNTER += 1
                        print(ref,output_string)
                    else:
                        print("ref:",ref,"pred:",output_string)

                    # write
                    out_file.write(lemma + "\t" +features+ "\t" + output_string + "\n")
                    out_file.flush()

                accuracy = COUNTER / LEN
                out_file.write("accuracy:"+ str(accuracy)+"\n")
                print(accuracy)

livles/csb-pol

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

config.json:   0%|          | 0.00/835 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

TypeError: T5ForConditionalGeneration.__init__() got an unexpected keyword argument 'dtype'