# Setup

In [29]:
%cd /dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5/
import sys
print(sys.version)
%rm -rf /usr/local/lib/python3.10/dist-packages/transformers/

/dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5
3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

In [1]:
# works
!pip uninstall transformers -y
!pip install transformers==4.36.2  datasets==4.3.0 accelerate==0.27.2
#!pip install transformers --upgrade
!pip install torch==2.9.1
!pip install ipywidgets==8.1.7
#!pip install torch torchvision --index-url https://download.pytorch.org/whl/cu120
!pip install python-dotenv==1.2.1 pickleshare==0.7.5

Found existing installation: transformers 4.57.1
Uninstalling transformers-4.57.1:
  Successfully uninstalled transformers-4.57.1
Collecting transformers==4.36.2
  Using cached transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (4.3.0)
Requirement already satisfied: accelerate==0.27.2 in /usr/local/lib/python3.10/dist-packages (0.27.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (2.32.3)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.36.2)
  Using cached tokenizers-0.15.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.2) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate==0.27.2) (5.9.8)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.27.2) (2.9.1)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (22.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.1)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2024.5.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.9.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets) (4.12.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets) (2024.6.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets) (3.7)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2) (4.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.19.3->transformers==4.36.2) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.36.2) (2.0.7)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)

Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.27.2) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx<1.0.0->datasets) (1.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate==0.27.2) (2.1.5)
Using cached transformers-4.36.2-py3-none-any.whl (8.2 MB)
Using cached tokenizers-0.15.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.1
    Uninstalling tokenizers-0.22.1:
      Successfully uninstalled tokenizers-0.22.1
Successfully installed tokenizers-0.15.2 transformers-4.36.2
Requirement already satisfied: torch==2.9.1 in /usr/local/lib/python3.10/dist-packages (2.9.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (4.12.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2024.5.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch==2.9.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.9.1) (2.1.5)
Requirement already satisfied: ipywidgets==8.1.7 in /usr/local/lib/python3.10/dist-packages (8.1.7)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (8.21.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (5.9.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (3.0.16)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.19.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (3.0.46)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (2.18.0)
Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.6.3)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (1.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (4.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.1.7) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.1.7) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.1.7) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (2.4.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (1.16.0)
Requirement already satisfied: python-dotenv==1.2.1 in /usr/local/lib/python3.10/dist-packages (1.2.1)
Requirement already satisfied: pickleshare==0.7.5 in /usr/local/lib/python3.10/dist-packages (0.7.5)

In [1]:
# works
!pip uninstall transformers -y
!pip install transformers==4.57.1  datasets accelerate==0.27.2
#!pip install transformers --upgrade
!pip install torch==2.9.1
!pip install ipywidgets==8.1.7
#!pip install torch torchvision --index-url https://download.pytorch.org/whl/cu120
!pip install python-dotenv==1.2.1 pickleshare==0.7.5

Found existing installation: transformers 4.57.1
Uninstalling transformers-4.57.1:
  Successfully uninstalled transformers-4.57.1
Collecting transformers==4.57.1
  Using cached transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (4.3.0)
Requirement already satisfied: accelerate==0.27.2 in /usr/local/lib/python3.10/dist-packages (0.27.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (2.32.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.57.1) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate==0.27.2) (5.9.8)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.27.2) (2.9.1)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (22.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.1)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2024.5.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.10/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.9.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets) (4.12.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets) (2024.6.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx<1.0.0->datasets) (3.7)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (4.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.57.1) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.57.1) (2.0.7)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate==0.27.2) (3.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (23.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.0.5)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (4.0.3)

Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch>=1.10.0->accelerate==0.27.2) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from anyio->httpx<1.0.0->datasets) (1.2.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate==0.27.2) (2.1.5)
Using cached transformers-4.57.1-py3-none-any.whl (12.0 MB)
Installing collected packages: transformers
Successfully installed transformers-4.57.1
Requirement already satisfied: torch==2.9.1 in /usr/local/lib/python3.10/dist-packages (2.9.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (4.12.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2024.5.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch==2.9.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.9.1) (2.1.5)
Requirement already satisfied: ipywidgets==8.1.7 in /usr/local/lib/python3.10/dist-packages (8.1.7)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (8.21.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (5.9.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.7) (3.0.16)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.19.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (3.0.46)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (2.18.0)
Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (0.6.3)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (1.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.7) (4.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.1.7) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.1.7) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.1.7) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (2.4.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets==8.1.7) (1.16.0)
Requirement already satisfied: python-dotenv==1.2.1 in /usr/local/lib/python3.10/dist-packages (1.2.1)
Requirement already satisfied: pickleshare==0.7.5 in /usr/local/lib/python3.10/dist-packages (0.7.5)

In [ ]:
 from dotenv import load_dotenv
import os

load_dotenv("../../.env",override=True)

HF_TOKEN = os.getenv("HF_TOKEN")

#print("HF_TOKEN: ", HF_TOKEN)

 # source: https://huggingface.co/docs/transformers/v4.28.1/tasks/summarization
 from huggingface_hub import login
#login()

In [40]:
#!pip uninstall transformers  accelerate torch -y
!rm -rf /usr/local/lib/python3.10/dist-packages/-andas*
!pip install torch==2.9.1  datasets==4.3.0  tiktoken==0.12.0 pandas==2.2.2 numpy==1.23.5 pyarrow==16.1.0
!pip install transformers==4.41.0
!pip install accelerate==1.11.0
!pip install ipywidgets==8.1.8
!pip install python-dotenv==8.1.8 pickleshare==0.7.5

Requirement already satisfied: torch==2.9.1 in /usr/local/lib/python3.10/dist-packages (2.9.1)
Requirement already satisfied: datasets==4.3.0 in /usr/local/lib/python3.10/dist-packages (4.3.0)
Collecting tiktoken==0.12.0
  Using cached tiktoken-0.12.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (6.7 kB)
Collecting pandas==2.2.2
  Using cached pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting numpy==1.23.5
  Using cached numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Collecting pyarrow==16.1.0
  Using cached pyarrow-16.1.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (4.12.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2024.5.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.9.1) (3.5.1)
INFO: pip is looking at multiple versions of datasets to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install datasets==4.3.0 and pyarrow==16.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pyarrow==16.1.0
    datasets 4.3.0 depends on pyarrow>=21.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Collecting transformers==4.41.0
  Downloading transformers-4.41.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.8/43.8 kB 912.5 kB/s eta 0:00:00 0:00:01
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (2.32.3)
Collecting tokenizers<0.20,>=0.19 (from transformers==4.41.0)
  Downloading tokenizers-0.19.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.0) (2024.5.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.0) (4.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.0) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.41.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.41.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.41.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.41.0) (2024.6.2)
Downloading transformers-4.41.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 49.8 MB/s eta 0:00:0000:0100:01
Downloading tokenizers-0.19.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 28.7 MB/s eta 0:00:00:00:01
Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.1
    Uninstalling tokenizers-0.22.1:
      Successfully uninstalled tokenizers-0.22.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.3
    Uninstalling transformers-4.57.3:
      Successfully uninstalled transformers-4.57.3
Successfully installed tokenizers-0.19.1 transformers-4.41.0
Requirement already satisfied: accelerate==1.11.0 in /usr/local/lib/python3.10/dist-packages (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate==1.11.0) (1.24.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==1.11.0) (24.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate==1.11.0) (5.9.8)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate==1.11.0) (6.0.1)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==1.11.0) (2.9.1)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==1.11.0) (0.36.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.10/dist-packages (from accelerate==1.11.0) (0.7.0)

Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.11.0) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.11.0) (2024.5.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.11.0) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.11.0) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.11.0) (4.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.10/dist-packages (from huggingface_hub>=0.21.0->accelerate==1.11.0) (1.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (1.13.1.3)
Requirement already satisfied: triton==3.5.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.0->accelerate==1.11.0) (3.5.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate==1.11.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.0.0->accelerate==1.11.0) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate==1.11.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate==1.11.0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate==1.11.0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface_hub>=0.21.0->accelerate==1.11.0) (2024.6.2)
Collecting ipywidgets==8.1.8
  Using cached ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (8.21.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (5.9.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /usr/local/lib/python3.10/dist-packages (from ipywidgets==8.1.8) (3.0.16)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (0.19.1)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (3.0.46)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (2.18.0)
Requirement already satisfied: stack-data in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (0.6.3)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (1.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=6.1.0->ipywidgets==8.1.8) (4.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.1.8) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.1.8) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets==8.1.8) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.8) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.8) (2.4.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.10/dist-packages (from stack-data->ipython>=6.1.0->ipywidgets==8.1.8) (0.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets==8.1.8) (1.16.0)
Using cached ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Installing collected packages: ipywidgets
  Attempting uninstall: ipywidgets
    Found existing installation: ipywidgets 8.1.7
    Uninstalling ipywidgets-8.1.7:
      Successfully uninstalled ipywidgets-8.1.7
Successfully installed ipywidgets-8.1.8
ERROR: Could not find a version that satisfies the requirement python-dotenv==8.1.8 (from versions: 0.1.0, 0.1.2, 0.1.3, 0.1.5, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.16.0, 0.17.0, 0.17.1, 0.18.0, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.21.0, 0.21.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1)
ERROR: No matching distribution found for python-dotenv==8.1.8

# Pre-training
with 10k sentences in Kashubian

In [35]:
# source: https://corpora.uni-leipzig.de/en?corpusId=csb_wikipedia_2021
# source: https://huggingface.co/docs/transformers/v4.57.1/en/model_doc/t5#transformers.T5Config
sentences_path = "/dss/dsshome1/03/ge87wod2/morphological-inflection/data/leipzig-corpera-collection/csb_wikipedia_2021_10K/" + "csb_wikipedia_2021_10K-sentences.txt"
import random
import math
with open (sentences_path,"r") as in_file:
   
    lines = in_file.readlines()
    for i in range(math.floor((len(lines)-1)/16)):
        if i == 4: break
        print(i)
        inputs = []
        labels = []
        batch_lines = lines[i*16:min(i*16+16,len(lines))]
        for line in batch_lines:
            sentence = line.split("\t")[1] # cut out line number
            words = sentence.split(" ")
            end_index = len(words)-4
            mask_len = 3
            while (end_index < 1 and mask_len > 0 ):
                mask_len -= 1
                end_index += 1
            start_index = random.randint(1,end_index) # mask 3 words: start mask between second and fourth last word
            input_sentence = words[:start_index] + ["<extra_id_0>"] + words[start_index+mask_len:]
            label_sentence = ["<extra_id_0>"]+words[start_index:start_index+mask_len]+["<extra_id_1>"]
            input_sentence = " ".join(input_sentence)
            label = " ".join(label_sentence)
            inputs.append(input_sentence)
            labels.append(label)
            from transformers import AutoTokenizer, T5ForConditionalGeneration, AutoModelForSeq2SeqLM
            tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
            model = T5ForConditionalGeneration.from_pretrained("google/byt5-small")

            # training
            input_ids = tokenizer(inputs, return_tensors="pt",padding=True).input_ids
            labels_batch = tokenizer(labels, return_tensors="pt",padding=True).input_ids
            outputs = model(input_ids=input_ids, labels=labels_batch)
            loss = outputs.loss
            logits = outputs.logits
print(inputs[0],labels[0])

# inference
input_ids = tokenizer(
    "The <extra_id_0> walks in <extra_id_1> park", return_tensors="pt"
).input_ids  # Batch size 1
outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))
# studies have shown that owning a dog is good for you.

FileNotFoundError: [Errno 2] No such file or directory: '/dss/dsshome1/03/ge87wod2/morphological-inflection/data/leipzig-corpera-collection/csb_wikipedia_2021_10K/csb_wikipedia_2021_10K-sentences.txt'

In [19]:
#input_ids = tokenizer("The dog chases a ball in the park.").input_ids
#masked_input = torch.tensor([input_ids[:8] + [258] + input_ids[14:21] + [257] + input_ids[28:]])
#print(input_ids)
#print(masked_input)
#output = model.generate(masked_input, max_length=100)

[87, 107, 104, 35, 103, 114, 106, 35, 102, 107, 100, 118, 104, 118, 35, 100, 35, 101, 100, 111, 111, 35, 108, 113, 35, 119, 107, 104, 35, 115, 100, 117, 110, 49, 1]
tensor([[ 87, 107, 104,  35, 103, 114, 106,  35, 258,  35, 100,  35, 101, 100,
         111, 111, 257,  35, 115, 100, 117, 110,  49,   1]])

In [3]:
# from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Trainer, TrainingArguments
from datasets import load_dataset

# Load domain-specific text (replace with your own corpus)
lang = "csb-pol-sent"
train_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json/data/{lang}_trn.tsv"
eval_path = f"/dss/dsshome1/03/ge87wod2/morphological-inflection/preprocessing/preprocessing_to_json/data/{lang}_dev.tsv"
dataset = load_dataset("csv", delimiter="\t",column_names=["input","labels"],data_files={"train": train_path,"validation": eval_path},quoting=3) # disable quote parsing


# Tokenizer
def preprocess_function(examples):
    # inputs = [prefix + doc for doc in examples["text"]]
    inputs = examples["input"]
    model_inputs = tokenizer(inputs)

    labels = tokenizer(text_target=examples["labels"],padding=True) # same length irrelevant here, so no truncation or padding

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenizer = AutoTokenizer.from_pretrained("google/byt5-small")
tokenized_dataset = dataset.map(preprocess_function, batched=True)

# Load pre-trained model
model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, return_tensors="pt")
# Training arguments
training_args = TrainingArguments (
    output_dir="./byt5_small/"+lang+"-6epochs",
    overwrite_output_dir=True,
    num_train_epochs=6,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    weight_decay=0.01,
    evaluation_strategy = "epoch",
    #predict_with_generate=True,
   # save_steps=10_000,
    save_total_limit=3,
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
)

# Pretrain the model
trainer.train()
trainer.push_to_hub()

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/livles/csb-pol-sent-6epochs/commit/161b095fb5b329c6f46fa30a29e7a72b9b1de28b', commit_message='End of training', commit_description='', oid='161b095fb5b329c6f46fa30a29e7a72b9b1de28b', pr_url=None, repo_url=RepoUrl('https://huggingface.co/livles/csb-pol-sent-6epochs', endpoint='https://huggingface.co', repo_type='model', repo_id='livles/csb-pol-sent-6epochs'), pr_revision=None, pr_num=None)

In [5]:
import torch
from transformers import AutoModelForSeq2SeqLM

model = AutoModelForSeq2SeqLM.from_pretrained("google/byt5-small")

num_special_tokens = 3

input_ids = torch.tensor([list("Life is like a box of chocolates.".encode("utf-8"))]) + num_special_tokens
labels = torch.tensor([list("La vie est comme une boîte de chocolat.".encode("utf-8"))]) + num_special_tokens
loss = model(input_ids, labels=labels).loss
loss.item()

2.658773899078369

# Training small pre-trained ByT5 model using dataset

In [28]:
LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"]
LANGS = LANGS[-2:]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul_2","amh","pol","ote"]
LANGS = ["mul-language-code","mul-language-word"]
LANGS = ["mul-language-code"]
LANGS = ["5lang-sample"]
#LANGS = ["slavic-family"]
LANGS = ["pol"]

PATH_JSON_DATA = "../preprocessing/preprocessing_to_json/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang.split("-")[0] + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # -

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    checkpoint = "livles/csb-pol-sent"
    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/"+checkpoint.split("/")[1]+"-"+lang,
        eval_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=4,
        predict_with_generate=True,
        # save_strategy="epoch",
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        # load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        processing_class=tokenizer,
        data_collator=data_collator,
        # compute_metrics=compute_metrics,
   
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Inflect zacny | ADJ;ACC(SG,FEM)', 'target': 'zacną'}

ImportError: cannot import name 'PreTrainedModel' from 'transformers' (/usr/local/lib/python3.10/dist-packages/transformers/__init__.py)

# Train with more epochs

In [8]:
!rm -rf /dss/dsshome1/03/ge87wod2/morphological-inflection/ByT5/byt5_small/*
LANGS = ["5lang-sample"]
#LANGS = ["slavic-family"]



PATH_JSON_DATA = "../preprocessing/preprocessing_to_json/data/"

for lang in LANGS:
    from datasets import load_dataset
    dataset = load_dataset("json", data_files={"train": PATH_JSON_DATA + lang + "_trn.json", "validation": PATH_JSON_DATA + lang + "_dev.json"})

    print(dataset["train"][0])

    from transformers import AutoTokenizer

    checkpoint = "google/byt5-small"
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    # 

    import torch

    from transformers import (
        AutoTokenizer,
        TrainingArguments,
        Trainer,
        AutoModelForSeq2SeqLM,
        Seq2SeqTrainingArguments,
        Seq2SeqTrainer
    )
    from datasets import load_dataset

    def preprocess_function(examples):
        # inputs = [prefix + doc for doc in examples["text"]]
        inputs = examples["input"]
        model_inputs = tokenizer(inputs)

        labels = tokenizer(text_target=examples["target"]) # same length irrelevant here, so no truncation or padding

        model_inputs["labels"] = labels["input_ids"]
        return model_inputs


    tokenized_dataset = dataset.map(preprocess_function, batched=True)
    print(tokenized_dataset)
    sample = tokenized_dataset["train"][0]
    print(sample["labels"])

    from transformers import DataCollatorForSeq2Seq

    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=checkpoint)

    from transformers import AutoModelForSeq2SeqLM, Seq2SeqTrainingArguments, Seq2SeqTrainer

    model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    training_args = Seq2SeqTrainingArguments(
        output_dir="byt5_small/"+lang+"_13epochs",
        eval_strategy="epoch",
        learning_rate=5e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        weight_decay=0.01,
        save_total_limit=3,
        num_train_epochs=13,
        predict_with_generate=True,
        fp16=False,# did not work with True #change to bf16=True for XPU 
        #bf16 = True, # performance was best without setting fp16 or bf16 to true
        push_to_hub=True,
        warmup_steps = 500,
        save_strategy="epoch",
        load_best_model_at_end=True, # otherwise not model with minimum loss during training, like https://huggingface.co/docs/transformers/tasks/sequence_classification,
        greater_is_better=False,
        metric_for_best_model="eval_loss"
    )

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"],
        tokenizer=tokenizer,
        data_collator=data_collator,
        # compute_metrics=compute_metrics,
    )

    trainer.train()
    trainer.push_to_hub()

{'input': 'Navajo: Inflect náʼáłkad | V;IND;PFV;NOM(1,GRPL)', 'target': 'ńdaʼiilkad'}
DatasetDict({
    train: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
    validation: Dataset({
        features: ['input', 'target', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1000
    })
})
[200, 135, 103, 100, 205, 191, 108, 108, 111, 110, 100, 103, 1]

/tmp/ipykernel_3401446/2533773261.py:79: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

# Testing models
+ [ ] TODO: finetune all slavic models and test them on the specific dataset
+ [ ] TODO: test 5lang-sample model on the dataset with prefixes

In [16]:
# SETTINGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng","mul","deu_eng"] + ["mul_2","ote","pol","amh"] + ["mul-language-code","mul-language-word"]
SETTINGS = ["mul"]
SETTINGS = ["5lang-sample"]
BASE_TEST_LANGUAGES_OF_SETTING = {"slavic":["pol","ces","csb","dsb","slk"],"slavic-word":["pol","ces","csb","dsb","slk"],"slavic-family":["pol","ces","csb","dsb","slk"],"5lang-sample":["deu","nav","klr","amh","grc"],"5lang-sample_16epochs":["deu","nav","klr","amh","grc"],
                                 "sme-15ksamples":["sme"],"sme-20ksamples":["sme"],"klr-15ksamples":["klr"],"klr-20ksamples":["klr"],"slavic-distant-word": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],"slavic-distant-word-or-family": ["pol","ces","csb","dsb","slk","mkd","rus","bel"],
                                  "csb-pol":["csb","pol"], "csb-pol-sent-pol":["csb","pol"]
                                 }
CODES = {"slavic": "","slavic-word":["-lang-word"],"slavic-family":["-family","-lang-word","-word-or-family"],"5lang-sample":["-lang-word"],"5lang-sample_16epochs":["-lang-word"],"5lang-sample_13epochs":["-lang-word"],"sme-15ksamples":[""],"sme-20ksamples":[""],"klr-15ksamples":[""],"klr-20ksamples":[""],"slavic-distant-word":["-lang-word"],"slavic-distant-word-or-family":["-lang-word"],"csb-pol":[""],"csb-pol-sent-pol":[""]}
SETTINGS = ["slavic","slavic-word"]
SETTINGS = ["sme-15ksamples","sme-20ksamples","klr-15ksamples","klr-20ksamples","5lang-sample_16epochs"]
SETTINGS = ["slavic-distant-word-or-family"]
SETTINGS = ["csb-pol-sent-pol"]

#TEST_LANGS_OLD = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] 
#TEST_LANGS = ["grc","dan","fra","sme","deu","nav","jap","klr","eng"] + ["ote","pol","amh","csb"]
#lang5_LANGS = ["deu","nav","klr","amh","grc"]
#lang_code = ""
for lang_setting in SETTINGS:
    test_langs = BASE_TEST_LANGUAGES_OF_SETTING[lang_setting]
    #if lang_setting == "mul": LANG_CODES = ["-language-word","-language-code",""] # test with no language code/word too
    #else: LANG_CODES = [""]
    #for lang_code in LANG_CODES:
        #if lang_setting in ( "deu_eng", "mul") and lang_code == "": test_langs = TEST_LANGS_OLD
        #elif lang_setting in ["mul_2","mul"]: test_langs = TEST_LANGS # test multilingual model on all languages it was trained on + Kashubian
        #elif lang_setting == "5lang-sample": test_langs = lang5_LANGS
        #elif lang_setting == "pol": test_langs = ["pol","csb"] # test Polish model on Kashubian also
        #else: 
    for lang_code in CODES[lang_setting]:
        for test_lang in test_langs:
            import torch
            from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
            PRETRAINED_MODEL = "google/byt5-small"
            FINETUNED_MODEL ="livles/"+lang_setting
            #FINETUNED_MODEL ="./byt5_small/"+lang_setting + lang_code
            MODEL = FINETUNED_MODEL
            print(MODEL)
            tokenizer = AutoTokenizer.from_pretrained(
                FINETUNED_MODEL,
            )
            model = AutoModelForSeq2SeqLM.from_pretrained(
                FINETUNED_MODEL,
            dtype=torch.float16,
            device_map="auto"
            )
            from datasets import load_dataset
            OUT_DIR = "output_byt5_small/" + lang_setting + "/" 
            PATH_TO_JSON_TEST_FILE = "../preprocessing/preprocessing_to_json/data/" + test_lang + lang_code+ "_tst.json"
            print("test file: ",PATH_TO_JSON_TEST_FILE)
            PATH_TO_ORIG_TEST_FILE = "../2023InflectionST/part1/data/" + test_lang + ".tst"
            from pathlib import Path
            Path(OUT_DIR).mkdir(parents=True, exist_ok=True)
            with open (OUT_DIR + test_lang + lang_code + "_byt5-small.out","w") as out_file, open (PATH_TO_ORIG_TEST_FILE, "r") as test_file:
                dataset = load_dataset("json",data_files={"test":PATH_TO_JSON_TEST_FILE})
                covered_test_lines = dataset["test"]["input"]
                LEN = len(covered_test_lines)
                COUNTER = 0

                # preds = map (generate,covered_test_lines)
                for line in covered_test_lines:
                    input_ids = tokenizer(line, return_tensors="pt").to(model.device)
                    output = model.generate(
                        **input_ids,
                        max_new_tokens=50,
                        num_beams=4,
                        #early_stopping=True
                    )
                    output_string = (tokenizer.decode(output[0], skip_special_tokens=True))
                    lemma, features, ref = test_file.readline().strip().split("\t")

                    # evaluate
                    if (ref == output_string):
                        COUNTER += 1
                        print(ref,output_string)
                    else:
                        print("ref:",ref,"pred:",output_string)

                    # write
                    out_file.write(lemma + "\t" +features+ "\t" + output_string + "\n")
                    out_file.flush()

                accuracy = COUNTER / LEN
                out_file.write("accuracy:"+ str(accuracy)+"\n")
                print(accuracy)

livles/csb-pol-sent-pol

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/791 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.20G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/152 [00:00<?, ?B/s]

test file:  ../preprocessing/preprocessing_to_json/data/csb_tst.json

Generating test split: 0 examples [00:00, ? examples/s]

ref: narzãdzacze pred: narzãdzôcze
ref: narzãdzaczom pred: narzãdzôczom
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczama pred: narzãdzôczami
ref: narzãdzaczu pred: narzãdzôczu
ref: narzãdzaczowi pred: narzãdzôczowi
ref: narzãdzacza pred: narzãdzôcza
ref: narzãdzaczach pred: narzãdzôczach
ref: narzãdzaczów pred: narzãdzôczy
ref: narzãdzaczã pred: narzãdzôczem
ref: narzãdzacze pred: narzãdzôcze
ref: narzãdzacza pred: narzãdzôcz
narzãdzôcz narzãdzôcz
ref: narzãdzacze pred: narzãdzôcze
ref: Jastrë pred: Jastrów
Jastrach Jastrach
ref: Jastróm pred: Jastrom
Jastrów Jastrów
ref: Jastrama pred: Jastrów
ref: Jastrë pred: Jastrów
ref: Jastrë pred: Jastry
ref: pòniedzałczi pred: pòniedzôłki
ref: pòniedzałkóm pred: pòniedzôłkom
ref: pòniedzałkù pred: pòniedzôłku
ref: pòniedzałkama pred: pòniedzôłkami
ref: pòniedzałkù pred: pòniedzôłcu
ref: poniedzałkòwi pred: pòniedzôłkowi
ref: pòniedzałkù pred: pòniedzôłka
ref: pòniedzałkach pred: pòniedzôłkach
ref: pòniedzałków pred: pòniedzôłków
ref: pòniedzałkã pred: pòniedzôłkiem
ref: pòniedzałczi pred: pòniedzôłki
pòniedzôłk pòniedzôłk
pòniedzôłk pòniedzôłk
ref: pòniedzałczi pred: pòniedzôłki
ref: pùjczi pred: pùjki
pùjkom pùjkom
ref: pùjkù pred: pùjku
ref: pùjkama pred: pùjkami
ref: pùjkù pred: pùjku
ref: pùjkòwi pred: pùjkowi
pùjka pùjka
pùjkach pùjkach
pùjków pùjków
ref: pùjkã pred: pùjkiem
ref: pùjczi pred: pùjki
ref: pùjka pred: pùjk
pùjk pùjk
ref: pùjczi pred: pùjki
ref: môlniczi pred: môlniki
ref: môlnikòm pred: môlnikom
ref: môlnikù pred: môlniku
ref: môlnikama pred: môlnikami
ref: môlnikù pred: môlniku
ref: môlnikòwi pred: môlnikowi
môlnika môlnika
môlnikach môlnikach
môlników môlników
ref: môlnikã pred: môlnikiem
ref: môlniczi pred: môlniki
môlnik môlnik
môlnik môlnik
ref: môlniczi pred: môlniki
ref: wòłiwaczë pred: wòłiwôcze
ref: wòłiwaczom pred: wòłiwôczom
ref: wòłiwaczu pred: wòłiwôczu
ref: wòłiwaczama pred: wòłiwôczami
ref: wòłiwaczu pred: wòłiwôczu
ref: wòłiwaczowi pred: wòłiwôczowi
ref: wòłiwacza pred: wòłiwôcza
ref: wòłiwaczach pred: wòłiwôczach
ref: wòłiwaczów pred: wòłiwôczów
ref: wòłiwaczã pred: wòłiwôczem
ref: wòłiwaczë pred: wòłiwôcze
ref: wòłiwacza pred: wòłiwôcz
wòłiwôcz wòłiwôcz
ref: wòłiwaczë pred: wòłiwôcze
ref: łżëkwiôtë pred: łżëkwiôty
ref: łżëkwiôtom pred: łżëkwiotom
ref: łżëkwiôce pred: łżëkwiocie
ref: łżëkwiôtama pred: łżëkwiotami
ref: łżëkwiôce pred: łżëkwiocie
ref: łżëkwiôtowi pred: łżëkwiotowi
ref: łżëkwiôta pred: łżëkwiotu
ref: łżëkwiôtach pred: łżëkwiotach
ref: łżëkwiôtów pred: łżëkwiotów
ref: łżëkwiôtã pred: łżëkwiotem
ref: łżëkwiôtë pred: łżëkwiôty
ref: łżëkwiôta pred: łżëkwiôt
łżëkwiôt łżëkwiôt
ref: łżëkwiôtë pred: łżëkwioty
ref: lëstopadniczi pred: lëstopadniki
ref: lëstopadnikòm pred: lëstopadnikom
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikama pred: lëstopadnikami
ref: lëstopadnikù pred: lëstopadniku
ref: lëstopadnikòwi pred: lëstopadnikowi
lëstopadnika lëstopadnika
lëstopadnikach lëstopadnikach
lëstopadników lëstopadników
ref: lëstopadnikã pred: lëstopadnikiem
ref: lëstopadniczi pred: lëstopadniki
ref: lëstopadnika pred: lëstopadnik
lëstopadnik lëstopadnik
ref: lëstopadniczi pred: lëstopadniki
ref: sobòtë pred: sobóty
ref: sobòtóm pred: sobótom
ref: sobòto pred: sobóto
ref: sobòtama pred: sobótami
ref: sobòce pred: sobóce
ref: sobòce pred: sobótze
ref: sobòtë pred: sobóty
ref: sobòtach pred: sobótach
ref: sobòtów pred: sobót
ref: sobòtã pred: sobótą
ref: sobòtë pred: sobòty
ref: sobòtã pred: sobótę
ref: sobòta pred: sobóta
ref: sobòtë pred: sobòty
ref: kònie pred: kóń
ref: kòniom pred: kóńom
ref: kòniu pred: kóń
ref: kòniama pred: kóńami
ref: kòniu pred: kóń
ref: kòniowi pred: kóńowi
ref: kònia pred: kóń
ref: kòniach pred: kóńach
ref: kòni pred: kóń
ref: kòniã pred: kóńem
ref: kònie pred: kóń
ref: kònia pred: kóń
kóń kóń
ref: kònie pred: kóń
ref: nazéwacze pred: nazéwôcze
ref: nazéwaczom pred: nazéwôczom
ref: nazéwaczu pred: nazéwôczu
ref: nazéwaczama pred: nazéwôczami
ref: nazéwaczu pred: nazéwôczu
ref: nazéwaczowi pred: nazéwôczowi
ref: nazéwacza pred: nazéwôcza
ref: nazéwaczach pred: nazéwôczach
ref: nazéwaczów pred: nazéwôczy
ref: nazéwaczã pred: nazéwôczem
ref: nazéwacze pred: nazéwôcze
ref: nazéwacza pred: nazéwôcz
nazéwôcz nazéwôcz
ref: nazéwacze pred: nazéwôcze
ref: piątczi pred: piątki
ref: piątkóm pred: piątkom
ref: piątkù pred: piątku
ref: piątkama pred: piątkami
ref: piątkù pred: piątku
ref: piątkòwi pred: piątkowi
ref: piątkù pred: piątka
piątkach piątkach
piątków piątków
ref: piątkã pred: piątkiem
ref: piątczi pred: piątki
piątk piątk
piątk piątk
ref: piątczi pred: piątki
ref: rënczi pred: rënki
ref: rënkóm pred: rënkom
ref: stolem pred: rënku
ref: rënkama pred: rënkami
ref: rënkù pred: rënku
ref: rënkòwi pred: rënkowi
ref: rënkù pred: rënka
rënkach rënkach
rënków rënków
ref: rënkã pred: rënkiem
ref: rënczi pred: rënki
rënk rënk
rënk rënk
ref: rënczi pred: rënki
ref: wtórczi pred: wtórki
ref: wtórkòm pred: wtórkom
ref: wtórkù pred: wtórku
ref: wtórkama pred: wtórkami
ref: wtórkù pred: wtórku
ref: wtórkòwi pred: wtórkowi
wtórka wtórka
wtórkach wtórkach
wtórków wtórków
ref: wtórkã pred: wtórkiem
ref: wtórczi pred: wtórki
wtórk wtórk
wtórk wtórk
ref: wtórczi pred: wtórki
ref: winowacze pred: winowôcze
ref: winowaczom pred: winowôczom
ref: winowaczu pred: winowôczu
ref: winowaczama pred: winowôczami
ref: winowaczu pred: winowôczu
ref: winowaczowi pred: winowôczowi
ref: winowacza pred: winowôcza
ref: winowaczach pred: winowôczach
ref: winowaczów pred: winowôczy
ref: winowaczã pred: winowôczem
ref: winowacze pred: winowôcze
ref: winowacza pred: winowôcz
winowôcz winowôcz
ref: winowacze pred: winowôcze
ref: òjcowie pred: òjcy
ref: òjcóm pred: òjcom
ref: òjcze pred: òjcu
ref: òjcama pred: òjcami
òjcu òjcu
ref: òjcu pred: òjcowi
òjca òjca
òjcach òjcach
òjców òjców
ref: òjcã pred: òjcem
òjcem òjcem
ref: òjców pred: òjcy
ref: òjca pred: òjc
òjc òjc
ref: òjcowie pred: òjcy
latawiska latawiska
ref: latawiskóm pred: latawiskom
ref: latawiskù pred: latawisko
ref: latawiskama pred: latawiskami
ref: latawiskù pred: latawisku
ref: latawiskù pred: latawiskowi
latawiska latawiska
latawiskach latawiskach
latawisków latawisków
ref: latawiskã pred: latawiskiem
latawiska latawiska
ref: latawiskò pred: latawisko
ref: latawiskò pred: latawisko
latawiska latawiska
ref: Jastra pred: Jastry
Jastrach Jastrach
ref: Jastróm pred: Jastrom
Jastrów Jastrów
ref: Jastrama pred: Jastry
ref: Jastra pred: Jastry
ref: Jastra pred: Jastry
ref: czerwińce pred: czerwińcy
czerwińcom czerwińcom
czerwińcu czerwińcu
ref: czerwińcama pred: czerwińcami
czerwińcu czerwińcu
czerwińcowi czerwińcowi
czerwińca czerwińca
czerwińcach czerwińcach
czerwińców czerwińców
ref: czerwińcã pred: czerwińcem
czerwińce czerwińce
ref: czerwińca pred: czerwińc
czerwińc czerwińc
ref: czerwińc pred: czerwińcy
ref: rujanë pred: rujany
rujanom rujanom
rujanie rujanie
ref: rujanama pred: rujanami
rujanie rujanie
rujanowi rujanowi
ref: rujana pred: rujanu
rujanach rujanach
rujanów rujanów
ref: rujanã pred: rujanem
ref: rujanë pred: rujany
ref: rujana pred: rujan
rujan rujan
ref: rujanë pred: rujany
ref: dôwacze pred: dôwôcze
ref: dôwaczom pred: dôwôczom
ref: dôwaczu pred: dôwôczu
ref: dôwaczama pred: dôwôczami
ref: dôwaczu pred: dôwôczu
ref: dôwaczowi pred: dôwôczowi
dôwôcza dôwôcza
ref: dôwaczach pred: dôwôczach
ref: dôwaczów pred: dôwôczy
ref: dôwaczã pred: dôwôczem
ref: dôwacze pred: dôwôcze
ref: dôwacza pred: dôwôcz
dôwôcz dôwôcz
ref: dôwacze pred: dôwôcze
ref: serca pred: serce
ref: sercóm pred: sercom
ref: serce pred: serco
ref: sercama pred: sercami
sercu sercu
ref: serce pred: sercu
ref: sercu pred: sercowi
serca serca
sercach sercach
serców serców
ref: serc pred: serców
ref: sercã pred: sercem
sercem sercem
ref: serca pred: serce
serce serce
serce serce
ref: serca pred: serce
ref: lëpince pred: lëpincy
lëpincom lëpincom
lëpincu lëpincu
ref: lëpincama pred: lëpincami
ref: lëpincu pred: lëpincie
lëpincowi lëpincowi
lëpinca lëpinca
lëpincach lëpincach
lëpinców lëpinców
ref: lëpincã pred: lëpincem
lëpince lëpince
lëpinc lëpinc
lëpinc lëpinc
ref: lëpince pred: lëpincy
ref: séwniczi pred: séwniki
ref: séwnikòm pred: séwnikom
ref: séwnikù pred: séwniku
ref: séwnikama pred: séwnikami
ref: séwnikù pred: séwniku
ref: séwnikòwi pred: séwnikowi

séwnika séwnika
séwnikach séwnikach
séwników séwników
ref: séwnikã pred: séwnikiem
ref: séwniczi pred: séwniki
ref: séwnika pred: séwnik
séwnik séwnik
ref: séwniczi pred: séwniki
ref: zélniczi pred: zélniki
ref: zélnikòm pred: zélnikom
ref: zélnikù pred: zélniku
ref: zélnikama pred: zélnikami
ref: zélnikù pred: zélniku
ref: zélnikòwi pred: zélnikowi
zélnika zélnika
zélnikach zélnikach
zélników zélników
ref: zélnikã pred: zélnikiem
ref: zélniczi pred: zélniki
ref: zélnika pred: zélnik
zélnik zélnik
ref: zélniczi pred: zélniki
ref: stëczniczi pred: stëczniki
ref: stëcznikòm pred: stëcznikom
ref: stëcznikù pred: stëczniku
ref: stëcznikama pred: stëcznikami
ref: stëcznikù pred: stëczniku
ref: stëcznikòwi pred: stëcznikowi
stëcznika stëcznika
stëcznikach stëcznikach
stëczników stëczników
ref: stëcznikã pred: stëcznikiem
ref: stëczniczi pred: stëczniki
ref: stëcznika pred: stëcznik
stëcznik stëcznik
ref: stëczniczi pred: stëczniki
ref: strzodë pred: strzody
ref: strzodóm pred: strzodom
ref: strzodo pred: strzodzie
ref: strzodama pred: strzodami
ref: strzodze pred: strzodzie
ref: strzodze pred: strzodzie
ref: strzodë pred: strzody
strzodach strzodach
ref: strzodów pred: strzod
ref: strzodã pred: strzodą
ref: strzodë pred: strzody
ref: strzodã pred: strzodę
strzoda strzoda
ref: strzodë pred: strzody
ref: maje pred: môje
ref: majom pred: môjom
ref: maju pred: môju
ref: majima pred: môjami
ref: maju pred: môju
ref: majowi pred: môjowi
ref: maja pred: môja
ref: majach pred: môjach
ref: majów pred: môjów
ref: majã pred: môjem
ref: maje pred: môje
môj môj
môj môj
ref: maje pred: môje
ref: strumianniczi pred: strumianniki
ref: strumiannikòm pred: strumiannikom
ref: strumiannikù pred: strumianniku
ref: strumiannikama pred: strumiannikami
ref: strumiannikù pred: strumianniku
ref: strumiannikòwi pred: strumiannikowi
strumiannika strumiannika
strumiannikach strumiannikach
strumianników strumianników
ref: strumiannikã pred: strumiannikiem
ref: strumianniczi pred: strumianniki
strumiannik strumiannik
strumiannik strumiannik
ref: strumianniczi pred: strumianniki
tidzénie tidzénie
ref: tidzénióm pred: tidzénom
tidzéniu tidzéniu
ref: tidzénama pred: tidzénami
tidzéniu tidzéniu
tidzéniowi tidzéniowi
tidzénia tidzénia
ref: tidzénach pred: tidzéniach
ref: tidzéniów pred: tidzéń
ref: tidzénã pred: tidzéniem
tidzénie tidzénie
tidzéń tidzéń
tidzéń tidzéń
tidzénie tidzénie
ref: czwôrtczi pred: czwôrtki
ref: czwôrtkóm pred: czwôrtkom
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkama pred: czwôrtkami
ref: czwôrtkù pred: czwôrtku
ref: czwôrtkòwi pred: czwôrtkowi
ref: czwôrtkù pred: czwôrtka
czwôrtkach czwôrtkach
czwôrtków czwôrtków
ref: czwôrtkã pred: czwôrtkiem
ref: czwôrtczi pred: czwôrtki
czwôrtk czwôrtk
czwôrtk czwôrtk
ref: czwôrtczi pred: czwôrtki
ref: kòtë pred: kòty
kòtom kòtom
ref: kòce pred: kòto
ref: kòtama pred: kòtami
ref: kòce pred: kòcie
kòtowi kòtowi
ref: kòtu pred: kòtowi
ref: kòta pred: kòtu
kòtach kòtach
kòtów kòtów
ref: kòtã pred: kòtem
ref: kòtë pred: kòty
ref: kòta pred: kòt
kòt kòt
ref: kòtë pred: kòty
ref: gromiczniczi pred: gromiczniki
ref: gromicznikòm pred: gromicznikom
ref: gromicznikù pred: gromiczniku
ref: gromicznikama pred: gromicznikami
ref: gromicznikù pred: gromiczniku
ref: gromicznikòwi pred: gromicznikowi
gromicznika gromicznika
gromicznikach gromicznikach
gromiczników gromiczników
ref: gromicznikã pred: gromicznikiem
ref: gromiczniczi pred: gromiczniki
ref: gromicznika pred: gromicznik
gromicznik gromicznik
ref: gromiczniczi pred: gromiczniki
rodzôcze rodzôcze
rodzôczom rodzôczom
rodzôczu rodzôczu
ref: rodzôczama pred: rodzôczami
rodzôczu rodzôczu
rodzôczowi rodzôczowi
rodzôcza rodzôcza
rodzôczach rodzôczach
ref: rodzôczów pred: rodzôczy
ref: rodzôczã pred: rodzôczem
rodzôcze rodzôcze
ref: rodzôcza pred: rodzôcz
rodzôcz rodzôcz
rodzôcze rodzôcze
niedzele niedzele
ref: niedzelóm pred: niedzelom
niedzelo niedzelo
ref: niedzelama pred: niedzelami
niedzeli niedzeli
niedzeli niedzeli
niedzeli niedzeli
niedzelach niedzelach
ref: niedzelów pred: niedzel
ref: niedzelã pred: niedzelą
niedzele niedzele
ref: niedzelã pred: niedzelę
niedzela niedzela
niedzele niedzele
ref: gòdniczi pred: gòdniki
ref: gòdnikòm pred: gòdnikom
ref: gòdnikù pred: gòdniku
ref: gòdnikama pred: gòdnikami
ref: gòdnikù pred: gòdniku
ref: gòdnikòwi pred: gòdnikowi
gòdnika gòdnika
gòdnikach gòdnikach
gòdników gòdników
ref: gòdnikã pred: gòdnikiem
ref: gòdniczi pred: gòdniki
ref: gòdnika pred: gòdnik
gòdnik gòdnik
ref: gòdniczi pred: gòdniki
ref: stolemë pred: stolemy
ref: stolemóm pred: stolemom
ref: stolem pred: stolemie
ref: stolemama pred: stolemami
stolemie stolemie
ref: stolemòwi pred: stolemowi
ref: stolema pred: stolemu
stolemach stolemach
stolemów stolemów
ref: stolemã pred: stolemem
ref: stolemów pred: stolemy
ref: stolema pred: stolem
stolem stolem
ref: stolemë pred: stolemy
0.3045186640471513
livles/csb-pol-sent-pol
test file:  ../preprocessing/preprocessing_to_json/data/pol_tst.json

Generating test split: 0 examples [00:00, ? examples/s]

bezgrzeszne bezgrzeszne
bezgrzeszne bezgrzeszne
bezgrzesznego bezgrzesznego
bezgrzesznego bezgrzesznego
bezgrzesznego bezgrzesznego
bezgrzesznej bezgrzesznej
bezgrzesznej bezgrzesznej
bezgrzesznej bezgrzesznej
bezgrzesznemu bezgrzesznemu
bezgrzesznemu bezgrzesznemu
bezgrzeszny bezgrzeszny
bezgrzesznych bezgrzesznych
bezgrzesznych bezgrzesznych
bezgrzesznych bezgrzesznych
bezgrzesznym bezgrzesznym
bezgrzesznym bezgrzesznym
bezgrzesznymi bezgrzesznymi
uchwytami uchwytami
uchwyt uchwyt
uchwytom uchwytom
uchwytowi uchwytowi
uchwytów uchwytów
uchwyty uchwyty
uchwyty uchwyty
uchwyty uchwyty
zdaniami podrzędnymi zdaniami podrzędnymi
zdania podrzędnego zdania podrzędnego
zdania podrzędne zdania podrzędne
zdania podrzędne zdania podrzędne
zdaniem podrzędnym zdaniem podrzędnym
zdanie podrzędne zdanie podrzędne
ref: zdaniu podrzędnym pred: zdaniu podrzędnemu
ref: zdań podrzędnych pred: zdania podrzędnych
będą nosili będą nosili
ref: będą nosiły pred: będziecie nosiły
będziecie nosili będziecie nosili
będziecie nosiły będziecie nosiły
będzie nosiła będzie nosiła
będzie nosił będzie nosił
będziesz nosiła będziesz nosiła
ref: niech nosi pred: będzie nosił
ref: noście pred: nosijcie
nosić nosić
nosiłabym nosiłabym
nosiłabyś nosiłabyś
nosiłaby nosiłaby
nosiłam nosiłam
nosiłbym nosiłbym
nosiłbyś nosiłbyś
nosiłeś nosiłeś
nosilibyście nosilibyście
nosilibyśmy nosilibyśmy
nosiliby nosiliby
nosiliście nosiliście
nosiliśmy nosiliśmy
nosili nosili
ref: nosiłoby pred: nosiłby
nosił nosił
nosiłyście nosiłyście
nosiły nosiły
ref: nosimy pred: nosiłyśmy
ref: nosisz pred: nosiłoś
ref: nośmy pred: nosimy
ref: nosząca pred: nosiłabyś
ref: noszące pred: nosilibyście
ref: noszące pred: nosilibyście
ref: noszący pred: nosilibyście
ref: noszą pred: nosiły
ref: noszenie pred: nosić
ref: noszeni pred: nosilibyście
ref: noszę pred: nosiłem
ref: noszona pred: nosiłabym
ref: noszone pred: nosące
ref: noszone pred: nosiłybyśmy
ref: noszono pred: nosiące
kosmonaucie kosmonaucie
kosmonaucie kosmonaucie
ref: kosmonauci pred: kosmonauty
kosmonautach kosmonautach
kosmonautą kosmonautą
kosmonauta kosmonauta
kosmonautę kosmonautę
ref: kosmonautów pred: kosmonauty
kosmonautów kosmonautów
kosmonauty kosmonauty
łączach łączach
łączami łączami
ref: łącza pred: łącze
łącze łącze
łącze łącze
ref: łącze pred: łączu
ref: łączu pred: łączowi
łączu łączu
rosołach rosołach
ref: rosołami pred: rosółami
ref: rosołem pred: rosółem
ref: rosole pred: rosół
rosół rosół
ref: rosołów pred: rosółów
ref: rosoły pred: rosóły
bękarcie bękarcie
ref: bękarcie pred: bękartowi
bękartach bękartach
bękartami bękartami
bękartom bękartom
ref: bękartowi pred: bękarce
bękartów bękartów
naukowa naukowa
naukowe naukowe
naukowe naukowe
naukowe naukowe
naukowego naukowego
naukowego naukowego
naukowego naukowego
naukowego naukowego
naukowej naukowej
naukowemu naukowemu
naukowemu naukowemu
naukowych naukowych
naukowych naukowych
naukowych naukowych
naukowym naukowym
naukowym naukowym
naukowymi naukowymi
szufladami szufladami
szufladą szufladą
szufladę szufladę
ref: szuflado pred: szufladzie
szuflady szuflady
szuflady szuflady
szuflady szuflady
rzepikami rzepikami
rzepikiem rzepikiem
rzepiki rzepiki
rzepik rzepik
rzepik rzepik
rzepików rzepików
rzepiku rzepiku
rzepiku rzepiku
ref: gnojach pred: gnójach
ref: gnojami pred: gnójami
ref: gnojem pred: gnójem
ref: gnoje pred: gnóje
ref: gnoje pred: gnóje
gnój gnój
gnój gnój
ref: gnojowi pred: gnójowi
ref: gnoju pred: gnóju
ref: gnoju pred: gnóju
winogronowe winogronowe
winogronowe winogronowe
winogronowe winogronowe
winogronowego winogronowego
winogronowego winogronowego
winogronowej winogronowej
winogronowej winogronowej
winogronowej winogronowej
winogronowemu winogronowemu
winogronowemu winogronowemu
winogronowy winogronowy
winogronowym winogronowym
winogronowym winogronowym
będą kleili będą kleili
będą kleiły będą kleiły
ref: będę kleiła pred: będziemy kleiła
ref: będę kleił pred: będziemy kleił
będziecie kleiły będziecie kleiły
będzie kleiło będzie kleiło
ref: będziemy kleili pred: będą kleili
ref: kleicie pred: kleiłyście
kleić kleić
kleiłabym kleiłabym
kleiłabyś kleiłabyś
kleiłam kleiłam
kleiłby kleiłby
kleiłem kleiłem
kleiłeś kleiłeś
kleilibyśmy kleilibyśmy
kleiliście kleiliście
kleiliśmy kleiliśmy
kleiło kleiło
kleił kleił
kleiłybyście kleiłybyście
kleiłyby kleiłyby
kleiłyście kleiłyście
kleiłyśmy kleiłyśmy
ref: kleimy pred: kleiłyśmy
klejąca klejąca
klejące klejące
ref: klejący pred: kleilibyście
klejący klejący
ref: kleją pred: kleiły
ref: klejeni pred: kleilibyście
ref: klejona pred: klejąca
ref: klejono pred: klejące
ref: klej pred: będziesz kleił
uczuciach uczuciach
uczuciami uczuciami
uczucia uczucia
uczucia uczucia
ref: uczucie pred: uczuciu
uczuciu uczuciu
edylach edylach
edylami edylami
ref: edyla pred: edylu
ref: edyli pred: edyle
edyl edyl
edylom edylom
ref: edylowie pred: edyle
edylu edylu
edylu edylu
tłumaczeniach tłumaczeniach
tłumaczenia tłumaczenia
tłumaczenia tłumaczenia
tłumaczeniem tłumaczeniem
tłumaczenie tłumaczenie
tłumaczenie tłumaczenie
tłumaczeniu tłumaczeniu
tłumaczeniu tłumaczeniu
plombą plombą
plomba plomba
plombę plombę
plombie plombie
plombie plombie
plomb plomb
plombo plombo
plomby plomby
plomby plomby
nieśmiertelną nieśmiertelną
nieśmiertelną nieśmiertelną
nieśmiertelnego nieśmiertelnego
nieśmiertelnej nieśmiertelnej
nieśmiertelnej nieśmiertelnej
nieśmiertelnej nieśmiertelnej
nieśmiertelnemu nieśmiertelnemu
nieśmiertelni nieśmiertelni
nieśmiertelnych nieśmiertelnych
nieśmiertelnych nieśmiertelnych
nieśmiertelnym nieśmiertelnym
kulach kulach
kulą kulą
kula kula
kule kule
kule kule
kuli kuli
ref: kuli pred: kuly
kul kul
brzoskwiniową brzoskwiniową
brzoskwiniowa brzoskwiniowa
brzoskwiniowe brzoskwiniowe
brzoskwiniowe brzoskwiniowe
brzoskwiniowego brzoskwiniowego
brzoskwiniowego brzoskwiniowego
brzoskwiniowego brzoskwiniowego
brzoskwiniowej brzoskwiniowej
brzoskwiniowej brzoskwiniowej
brzoskwiniowi brzoskwiniowi
brzoskwiniowy brzoskwiniowy
brzoskwiniowych brzoskwiniowych
brzoskwiniowych brzoskwiniowych
brzoskwiniowych brzoskwiniowych
brzoskwiniowym brzoskwiniowym
brzoskwiniowymi brzoskwiniowymi
istnieniach istnieniach
istnienia istnienia
istnienia istnienia
istnienia istnienia
istnienie istnienie
istnienie istnienie
istnieniom istnieniom
ref: istnień pred: istnieni
martwą martwą
martwa martwa
martwe martwe
martwe martwe
martwego martwego
martwego martwego
martwemu martwemu
martwemu martwemu
martwi martwi
martwy martwy
martwy martwy
martwych martwych
martwych martwych
martwym martwym
martwym martwym
martwym martwym
martwym martwym
martwymi martwymi
napięciach napięciach
napięcia napięcia
napięcia napięcia
napięcia napięcia
napięcie napięcie
napięciu napięciu
ref: napięć pred: napięci
dziwce dziwce
dziwkami dziwkami
dziwką dziwką
dziwki dziwki
dziwki dziwki
dziwkom dziwkom
dziwko dziwko
kompromisem kompromisem
kompromisie kompromisie
kompromisie kompromisie
kompromis kompromis
kompromisom kompromisom
kompromisowi kompromisowi
kompromisów kompromisów
kompromisu kompromisu
kompromisy kompromisy
klanami klanami
klanem klanem
klanie klanie
klan klan
klanom klanom
klanowi klanowi
klany klany
klany klany
klany klany
polanach polanach
polanami polanami
polana polana
polanę polanę
polanie polanie
polanie polanie
polanom polanom
ref: polano pred: polanie
polany polany
polany polany
ref: niech wyrządzą pred: będą wyrządzili
ref: niech wyrządzę pred: będziemy wyrządziły
ref: wyrządzeni pred: wyrządzilibyście
ref: wyrządzę pred: będziemy wyrządziły
wyrządziłabym wyrządziłabym
wyrządziłabyś wyrządziłabyś
wyrządziłaś wyrządziłaś
wyrządziła wyrządziła
wyrządziłbym wyrządziłbym
wyrządziłbyś wyrządziłbyś
wyrządziłby wyrządziłby
wyrządziłeś wyrządziłeś
wyrządzilibyście wyrządzilibyście
wyrządzilibyśmy wyrządzilibyśmy
wyrządziliby wyrządziliby
wyrządziliście wyrządziliście
wyrządziliśmy wyrządziliśmy
ref: wyrządziłoby pred: wyrządziłby
wyrządził wyrządził
wyrządziłybyśmy wyrządziłybyśmy
wyrządziłyście wyrządziłyście
wyrządziłyśmy wyrządziłyśmy
wyrządziły wyrządziły
ref: wyrządzimy pred: będziemy wyrządziły
wyrządzona wyrządzona
wyrządzone wyrządzone
wyrządzono wyrządzono
ref: wyrządź pred: będziesz wyrządził
niższą niższą
niższa niższa
niższe niższe
niższe niższe
niższego niższego

niższego niższego
niższej niższej
niższemu niższemu
niższych niższych
niższym niższym
niższym niższym
niższym niższym
niższym niższym
nastolatkach nastolatkach
nastolatkami nastolatkami
nastolatka nastolatka
nastolatki nastolatki
nastolatki nastolatki
ref: nastolatków pred: nastolatki
nastolatku nastolatku
zbiegach zbiegach
ref: zbiega pred: zbieg
zbieg zbieg
zbiegom zbiegom
ref: zbiegowie pred: zbiegi
ref: zbiegów pred: zbiegi
zbiegu zbiegu
ref: szkutnicy pred: szkutniki
szkutnikach szkutnikach
szkutnikami szkutnikami
szkutnika szkutnika
szkutnikom szkutnikom
szkutników szkutników
szkutniku szkutniku
samotniejsi samotniejsi
samotniejszą samotniejszą
samotniejszą samotniejszą
samotniejsza samotniejsza
samotniejsze samotniejsze
samotniejsze samotniejsze
samotniejsze samotniejsze
samotniejszego samotniejszego
samotniejszego samotniejszego
samotniejszej samotniejszej
samotniejszej samotniejszej
samotniejszemu samotniejszemu
samotniejszy samotniejszy
samotniejszy samotniejszy
samotniejszych samotniejszych
samotniejszych samotniejszych
samotniejszym samotniejszym
samotniejszym samotniejszym
samotniejszymi samotniejszymi
mitozach mitozach
mitoza mitoza
mitozę mitozę
mitozie mitozie
mitozom mitozom
mitozy mitozy
asemblerach asemblerach
asemblerami asemblerami
asemblera asemblera
asemblerowi asemblerowi
asemblerów asemblerów
asemblery asemblery
asemblery asemblery
asemblerze asemblerze
asemblerze asemblerze
automacie automacie
automatami automatami
automat automat
automatowi automatowi
automaty automaty
automaty automaty
kasztanach kasztanach
kasztanami kasztanami
kasztan kasztan
kasztan kasztan
kasztany kasztany
kasztany kasztany
ref: śródmózgowiach pred: śródmózgowcach
ref: śródmózgowiami pred: śródmózgowcami
śródmózgowia śródmózgowia
śródmózgowie śródmózgowie
śródmózgowie śródmózgowie
ref: śródmózgowi pred: śródmózgowców
ref: śródmózgowiu pred: śródmózgowcowi
ref: śródmózgowiu pred: śródmózgowcu
ref: lisiąt pred: lisień
ref: lisięciem pred: lisiącą
ref: lisięciu pred: lisię
ref: lisięciu pred: lisię
lisię lisię
lisię lisię
ref: lisiętach pred: lisięch
ref: lisiętami pred: lisięmi
ref: lisięta pred: lisie
ref: lisięta pred: lisię
ref: lisiętom pred: lisiom
ref: graniach pred: granach
ref: granią pred: graną
granie granie
granie granie
ref: grani pred: grania
grań grań
basach basach
basie basie
basie basie
bas bas
bas bas
basy basy
woskowiną woskowiną
woskowina woskowina
ref: woskowino pred: woskowinie
ref: zadadzą pred: będą zadały
sinologia sinologia
sinologię sinologię
sinologii sinologii
sinologii sinologii
sinologii sinologii
sinologio sinologio
kurami kurami
kur kur
kurom kurom
kurowi kurowi
kurów kurów
kurze kurze
kurze kurze
przysięgach przysięgach
przysięgami przysięgami
przysięga przysięga
przysięgi przysięgi
przysięgom przysięgom
przysięgo przysięgo
nonanem nonanem
nonanie nonanie
nonan nonan
nonan nonan
nonanów nonanów
nonany nonany
elektrowniami elektrowniami
elektrownie elektrownie
elektrownie elektrownie
elektrownie elektrownie
ref: elektrowni pred: elektrownii
elektrowni elektrowni
elektrowniom elektrowniom
fotografach fotografach
fotografami fotografami
fotografem fotografem
fotografie fotografie
fotograf fotograf
ref: fotografów pred: fotografy
będą machały będą machały
ref: będę machała pred: będziemy machała
ref: będę machał pred: będziemy machał
ref: będziecie machali pred: będą machali
będzie machała będzie machała
będzie machało będzie machało
będzie machał będzie machał
ref: będziemy machali pred: będą machali
będziemy machały będziemy machały
będziesz machała będziesz machała
będziesz machał będziesz machał
ref: machający pred: machalibyście
ref: machający pred: machane
machajcie machajcie
machajmy machajmy
machałaby machałaby
machałam machałam
machałaś machałaś
machała machała
machałbym machałbym
machałby machałby
machałem machałem
machalibyście machalibyście
machalibyśmy machalibyśmy
machaliśmy machaliśmy
ref: machałoby pred: machałby
machałybyśmy machałybyśmy
ref: machałyby pred: machaliby
machałyście machałyście
machałyśmy machałyśmy
machały machały
ref: macham pred: machałem
machane machane
machanie machanie
ref: machani pred: machalibyście
machano machano
ref: machasz pred: machało
ref: niech macha pred: będzie machał
jonosferach jonosferach
jonosfera jonosfera
jonosferom jonosferom
jonosfery jonosfery
jonosfery jonosfery
jonosfery jonosfery
jonosferze jonosferze
ref: lodach pred: lódach
ref: lodem pred: lódem
lód lód
ref: lodom pred: lódom
ref: lodowi pred: lódowi
ref: lodów pred: lódów
ref: lodzie pred: lódzie
ref: będą siąknąły pred: będą siąknęły
będą siąknęli będą siąknęli
ref: będziemy siąknęli pred: będą siąknęli
ref: będzie siąknąła pred: będzie siąknęła
ref: będzie siąknąło pred: będzie siąknęło
ref: będzie siąknął pred: będzie siąknęł
ref: będziesz siąknąła pred: będziesz siąknęła
będziesz siąknął będziesz siąknął
ref: niech siąkną pred: będą siąknęli
ref: niech siąknie pred: będzie siąknęło
siąknąca siąknąca
siąknące siąknące
siąknące siąknące
siąknący siąknący
ref: siąknąłabyś pred: siąknęłabyś
ref: siąknąłaby pred: siąknęłaby
ref: siąknąła pred: siąknęła
siąknąłbyś siąknąłbyś
ref: siąknąłeś pred: siąknęłeś
siąknąłybyście siąknąłybyście
siąknąłybyśmy siąknąłybyśmy
ref: siąknąłyby pred: siąknęłyby
siąknąłyśmy siąknąłyśmy
ref: siąkną pred: siąknęły
ref: siąknęlibyście pred: siąknąlibyście
ref: siąknęlibyśmy pred: siąknąlibyśmy
ref: siąknęliście pred: siąknąliście
ref: siąknęliśmy pred: siąknąliśmy
ref: siąknę pred: siąknęłam
ref: siąkniemy pred: siąknąłyśmy
ref: siąkniesz pred: siąknęło
ref: siąknie pred: siąknęło
ref: siąknijcie pred: niech siąkną
ref: siąknijmy pred: niech siąkną
ref: siąknij pred: będziesz siąknęło
najdzikszą najdzikszą
najdziksza najdziksza
najdziksze najdziksze
najdziksze najdziksze
najdzikszego najdzikszego
najdzikszej najdzikszej
najdzikszej najdzikszej
najdzikszej najdzikszej
najdzikszemu najdzikszemu
najdzikszy najdzikszy
najdzikszy najdzikszy
najdzikszych najdzikszych
najdzikszych najdzikszych
najdzikszym najdzikszym
peronach peronach
peronem peronem
peronie peronie
peronom peronom
peronów peronów
perony perony
sygnałach sygnałach
sygnałami sygnałami
sygnał sygnał
sygnałom sygnałom
sygnały sygnały
sygnały sygnały
najlżejszą najlżejszą
najlżejsza najlżejsza
najlżejsze najlżejsze
najlżejsze najlżejsze
najlżejsze najlżejsze
najlżejszego najlżejszego
najlżejszego najlżejszego
najlżejszej najlżejszej
najlżejszemu najlżejszemu
najlżejszy najlżejszy
najlżejszych najlżejszych
najlżejszych najlżejszych
najlżejszym najlżejszym
najlżejszymi najlżejszymi
wybuchach wybuchach
wybuchem wybuchem
wybuch wybuch
wybuch wybuch
wybuchowi wybuchowi
wybuchu wybuchu
wybuchu wybuchu
wybuchu wybuchu
wybuchy wybuchy
wybuchy wybuchy
ref: sekście pred: sekstie
ref: sekście pred: seksce
sekstą sekstą
seksta seksta
sekst sekst
sekstom sekstom
seksto seksto
seksty seksty
seksty seksty
seksty seksty
bocianach bocianach
bocianami bocianami
bociana bociana
bocianem bocianem
bocianie bocianie
bocian bocian
bocianom bocianom
bocianów bocianów
bociany bociany
bociany bociany
trwania trwania
trwanie trwanie
trwanie trwanie
trwaniu trwaniu
trwaniu trwaniu
ref: będę marła pred: będziemy mrzeła
ref: będziecie marli pred: będziecie mrzeli
ref: będziecie marły pred: będziecie mrzeli
ref: będzie marła pred: będzie mrzeła
ref: będzie marło pred: będzie mrzeło
ref: będzie marł pred: będzie mrzeł
ref: będziemy marli pred: będą mrzeli
ref: marcie pred: mrzenie
ref: marłabyś pred: mrzełabyś
ref: marłam pred: mrzełam
ref: marłaś pred: mrzełaś
ref: marła pred: mrzeła
ref: marłbyś pred: mrzełbyś
ref: marłby pred: mrzełby
ref: marłeś pred: mrzełeś
ref: marlibyście pred: mrzelibyście
ref: marlibyśmy pred: mrzelibyśmy
ref: marł pred: mrzeł
ref: marłyby pred: mrzeliby
ref: marłyśmy pred: mrzełyśmy
ref: marły pred: mrzeły
ref: mrące pred: mrzące
ref: mrące pred: mrzące
ref: mrąc pred: mrzenie
ref: mrący pred: mrzelibyście
ref: mrący pred: mrzenie
ref: mrzecie pred: mrzełyście
mrzeć mrzeć
ref: mrzemy pred: mrząłyśmy
ref: mrze pred: mrzeło
ref: mrzyjcie pred: niech mrzą
ref: mrzyj pred: będziesz mrzeł
ref: niech mrą pred: będziemy mrzeli
ref: niech mrze pred: będzie mrzeł
oczopląsach oczopląsach
oczopląs oczopląs
oczopląsowi oczopląsowi
oczopląsy oczopląsy

przewodniczącego przewodniczącego
ref: przewodniczących pred: przewodniczące
przewodniczących przewodniczących
przewodniczącym przewodniczącym
ref: przewodniczący pred: przewodniczące
ref: przewodniczący pred: przewodniczące
mięczakach mięczakach
mięczakami mięczakami
ref: mięczaka pred: mięczak
mięczaka mięczaka
mięczakiem mięczakiem
mięczaki mięczaki
mięczaki mięczaki
mięczaki mięczaki
mięczak mięczak
mięczakowi mięczakowi
mięczaków mięczaków
nieodpowiedzialna nieodpowiedzialna
nieodpowiedzialne nieodpowiedzialne
nieodpowiedzialne nieodpowiedzialne
nieodpowiedzialne nieodpowiedzialne
nieodpowiedzialne nieodpowiedzialne
nieodpowiedzialnego nieodpowiedzialnego
nieodpowiedzialnego nieodpowiedzialnego
nieodpowiedzialnego nieodpowiedzialnego
nieodpowiedzialnemu nieodpowiedzialnemu
nieodpowiedzialnemu nieodpowiedzialnemu
nieodpowiedzialni nieodpowiedzialni
nieodpowiedzialny nieodpowiedzialny
nieodpowiedzialnych nieodpowiedzialnych
nieodpowiedzialnym nieodpowiedzialnym
nieodpowiedzialnym nieodpowiedzialnym
nieodpowiedzialnymi nieodpowiedzialnymi
szalu szalu
cyrkami cyrkami
cyrkiem cyrkiem
cyrki cyrki
cyrk cyrk
cyrk cyrk
cyrków cyrków
cyrku cyrku
ref: cyrku pred: cyrka
cyrku cyrku
najjaśniejsi najjaśniejsi
najjaśniejszą najjaśniejszą
najjaśniejsza najjaśniejsza
najjaśniejsze najjaśniejsze
najjaśniejsze najjaśniejsze
najjaśniejszego najjaśniejszego
najjaśniejszej najjaśniejszej
najjaśniejszej najjaśniejszej
najjaśniejszych najjaśniejszych
najjaśniejszych najjaśniejszych
najjaśniejszych najjaśniejszych
najjaśniejszym najjaśniejszym
najjaśniejszym najjaśniejszym
żenecie żenecie
żenetami żenetami
żenetą żenetą
żeneta żeneta
żenetę żenetę
żenet żenet
żenetom żenetom
żenety żenety
żenety żenety
żenety żenety
waściach waściach
waściami waściami
waści waści
ref: waści pred: waście
waści waści
waści waści
waści waści
waść waść
ref: otwarci pred: otwarty
otwartą otwartą
otwarta otwarta
otwarte otwarte
otwarte otwarte
otwartego otwartego
otwartej otwartej
otwartej otwartej
otwartej otwartej
otwartemu otwartemu
otwartemu otwartemu
ref: otwarty pred: otwartego
otwarty otwarty
otwartych otwartych
otwartym otwartym
otwartym otwartym
otwartymi otwartymi
ref: dłużnicy pred: dłużniki
ref: dłużnicy pred: dłużniki
dłużnikami dłużnikami
dłużnika dłużnika
dłużnik dłużnik
dłużnikowi dłużnikowi
ref: manicure'ami pred: manicurami
ref: manicure'em pred: manicurem
manicure manicure
ref: manicure'om pred: manicurom
ref: manicure'y pred: manicury
ref: manicure'y pred: manicury
ref: manicure'y pred: manicura
manicurze manicurze
sefardyjscy sefardyjscy
sefardyjski sefardyjski
ref: sefardyjskich pred: sefardyjscych
sefardyjskie sefardyjskie
sefardyjskiego sefardyjskiego
sefardyjskiego sefardyjskiego
sefardyjskiej sefardyjskiej
sefardyjskiej sefardyjskiej
sefardyjskiemu sefardyjskiemu
sefardyjskim sefardyjskim
sefardyjskim sefardyjskim
sefardyjskim sefardyjskim
sefardyjskimi sefardyjskimi
szynce szynce
szynce szynce
szynek szynek
szynkami szynkami
szynkę szynkę
szynki szynki
szynkom szynkom
szynko szynko
częstokołach częstokołach
częstokołami częstokołami
ref: częstokole pred: częstokolu
częstokół częstokół
tulem tulem
tul tul
tulowi tulowi
tulu tulu
tulu tulu
ścianami ścianami
ściana ściana
ścianę ścianę
ścianom ścianom
ściano ściano
ściany ściany
ściany ściany
ref: baracheł pred: barachłów
barachłach barachłach
barachła barachła
barachła barachła
barachła barachła
barachło barachło
barachło barachło
ref: barachłu pred: barachłowi
czczą czczą
czcza czcza
czcze czcze
czcze czcze
czcze czcze
czczego czczego
czczej czczej
czczej czczej
czczy czczy
czczych czczych
czczym czczym
czczym czczym
czczymi czczymi
ref: Indianach pred: Indianinach
ref: Indianie pred: Indianiny
Indianinie Indianinie
Indianinie Indianinie
Indianin Indianin
Indianinowi Indianinowi
ref: Indian pred: Indianiny
hodowlach hodowlach
hodowlą hodowlą
hodowla hodowla
hodowle hodowle
hodowli hodowli
hodowli hodowli
hodowli hodowli
hodowlom hodowlom
ref: pacie pred: patze
ref: pacie pred: patu
patami patami
ref: pata pred: pat
pat pat
patowi patowi
patów patów
paty paty
ilustracjach ilustracjach
ilustracje ilustracje
ilustracje ilustracje
ilustracji ilustracji
ilustracjom ilustracjom
ref: ilustracjo pred: ilustracji
rachunek rachunek
rachunek rachunek
rachunkach rachunkach
rachunkiem rachunkiem
rachunki rachunki
rachunkowi rachunkowi
rachunków rachunków
rachunku rachunku
rachunku rachunku
zimową zimową
zimową zimową
zimowa zimowa
zimowe zimowe
zimowe zimowe
zimowego zimowego
zimowego zimowego
zimowego zimowego
zimowej zimowej
zimowemu zimowemu
zimowy zimowy
zimowy zimowy
zimowych zimowych
zimowych zimowych
zimowym zimowym
zimowym zimowym
zimowym zimowym
rutenem rutenem
ruten ruten
chrabąszczach chrabąszczach
chrabąszczami chrabąszczami
ref: chrabąszcza pred: chrabąszcz
chrabąszczem chrabąszczem
chrabąszcze chrabąszcze
chrabąszcze chrabąszcze
chrabąszczom chrabąszczom
chrabąszczowi chrabąszczowi
ref: chrabąszczy pred: chrabąszczów
miarami miarami
miarę miarę
miar miar
miarom miarom
ref: miaro pred: miarze
miary miary
miary miary
ref: mierze pred: miarze
dzieżach dzieżach
dzieżami dzieżami
dzieżą dzieżą
dzieże dzieże
dzieże dzieże
dzieżom dzieżom
dzieżo dzieżo
dzieży dzieży
dzieży dzieży
małpeczce małpeczce
małpeczkach małpeczkach
małpeczkami małpeczkami
małpeczki małpeczki
małpeczkom małpeczkom
małpeczko małpeczko
koronach koronach
koroną koroną
korona korona
koronę koronę
koronie koronie
koronom koronom
ref: korono pred: koronie
korony korony
korony korony
korony korony
lipca lipca
ref: lipce pred: lipiece
ref: lipce pred: lipcy
ref: lipce pred: lipiecy
lipcom lipcom
ref: lipców pred: lipieców
lipiec lipiec
ref: lipiec pred: lipc
zupami zupami
zupą zupą
zupa zupa
zupie zupie
zup zup
zupo zupo
zupy zupy
zupy zupy
ref: miocie pred: mioto
miotach miotach
miotami miotami
miot miot
miotom miotom
miotowi miotowi
miotu miotu
mioty mioty
mioty mioty
mioty mioty
0.79